SIT=https://voabstsit.crm11.dynamics.com/
UAT=https://voabstuat.crm11.dynamics.com/
PPE=https://voabstppe.crm11.dynamics.com/
MO=https://voabstmo.crm11.dynamics.com/
DEFAULT=https://voabstsit.crm11.dynamics.com/
HotFixEnv=https://voabsthfx-rel.crm11.dynamics.com/
FAT=https://voa-bst-ct-fat.crm11.dynamics.com/
TRN=https://voabsttrn.crm11.dynamics.com/
DEV=https://voabstdev.crm11.dynamics.com/
WAVE=https://voa-ctp-dev-wave.crm11.dynamics.com/

#LAPortalURLS
LAPortal_SIT=https://voabstsit.powerappsportals.com/
LAPortal_PPE=https://laportal-preprod.hmrc.gov.uk/

