// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace POMSeleniumFrameworkPoc1.Features.UI.E2E
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Borderline NDR to CT")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("UI")]
    public partial class BorderlineNDRToCTFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "UI"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/UI/E2E", "Borderline NDR to CT", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "BorderlineNDRToCT.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/UI/E2E/BorderlineNDRToCT.feature", 5);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("NDRtoCT01_CTPRELMGMT-1553_CTPRELMGMT-1591_CTPRELMGMT-1580-Borderline NDR to CT Ra" +
            "ised Internally")]
        [global::NUnit.Framework.CategoryAttribute("BorderlineNDRtoCT")]
        [global::NUnit.Framework.CategoryAttribute("E2E")]
        [global::NUnit.Framework.CategoryAttribute("P1_A")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        [global::NUnit.Framework.CategoryAttribute("mini_Regression")]
        [global::NUnit.Framework.CategoryAttribute("HP_E2E")]
        public async global::System.Threading.Tasks.Task NDRtoCT01_CTPRELMGMT_1553_CTPRELMGMT_1591_CTPRELMGMT_1580_BorderlineNDRToCTRaisedInternally()
        {
            string[] tagsOfScenario = new string[] {
                    "BorderlineNDRtoCT",
                    "E2E",
                    "P1_A",
                    "Regression",
                    "mini_Regression",
                    "HP_E2E"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("NDRtoCT01_CTPRELMGMT-1553_CTPRELMGMT-1591_CTPRELMGMT-1580-Borderline NDR to CT Ra" +
                    "ised Internally", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
 await testRunner.GivenAsync("User uses test data with ID \'NP_001\' from \'Borderline NDR to CT\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
 await testRunner.GivenAsync("User is logged in to Dynamics application to work for \"Borderline_NDR to CT_E2E_F" +
                        "low\" case", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
 await testRunner.AndAsync("User collapse if site map navigation expanded on left pane", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
 await testRunner.GivenAsync("User click on \'Requests\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
 await testRunner.AndAsync("User looked for \'Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
 await testRunner.AndAsync("User entered 0 days before date for \'Date Received\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
 await testRunner.AndAsync("User entered 25 days before date for \'Proposed Effective Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
 await testRunner.AndAsync("User enter data for \'BA Report Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.AndAsync("User enter data for \'Reason For Validation\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
 await testRunner.AndAsync("User looked for \'Submitted By\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
 await testRunner.AndAsync("User looked for \'Data Source Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
 await testRunner.AndAsync("User scroll to \'New Hereditament Details\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
 await testRunner.AndAsync("User click on \'Find Address\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
 await testRunner.AndAsync("user enters data in \"Postcode\" and selects unique address in \'scenarioContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
 await testRunner.AndAsync("User enter data for \'Proposed Billing Authority\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
 await testRunner.AndAsync("User scroll to \'Billing Authority Link\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
 await testRunner.AndAsync("User enter random number for \'Proposed BA Reference Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
 await testRunner.AndAsync("User clicks on \'Validate Request\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
 await testRunner.AndAsync("User clicks on \'Proceed\' button on \'Confirm\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
 await testRunner.AndAsync("User click on \'Related Jobs\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
 await testRunner.AndAsync("User captures \"Job ID\" and \"Job Name\" in \"featureContext\" by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
 await testRunner.GivenAsync("User click on \'Jobs\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
 await testRunner.AndAsync("User \'Assign\' \'Job Name\' through \'All Jobs\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
    await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
 await testRunner.AndAsync("User click on \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
 await testRunner.AndAsync("User waits till \'Details\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
 await testRunner.AndAsync("User click on \'Set Effective Date\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
 await testRunner.AndAsync("User entered 5 days before hereditament \'Proposed Effective Date\' for  from calen" +
                        "der for \'New Proposed Effective Date\' field value on \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
 await testRunner.AndAsync("User enter \'Automation testing \' in \'New Effective Date Reason\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
 await testRunner.AndAsync("User click on \'Save\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
 await testRunner.AndAsync("User click on \'Submit\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
 await testRunner.AndAsync("User closes dialog if still present", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
 await testRunner.AndAsync("User validate \'New Proposed Effective Date\' value display for \'Proposed Effective" +
                        " Date\' from feature context", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Details\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
 await testRunner.AndAsync("User waits till \'Researching\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
 await testRunner.AndAsync("User validate \'New Proposed Effective Date\' value display for \'Proposed Effective" +
                        " Date\' from feature context", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
 await testRunner.AndAsync("User clicked on \'PVT\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
 await testRunner.AndAsync("User clicked on \'Create\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
 await testRunner.AndAsync("User looked for value \'19 - Houses and Bungalows\' in \'Group\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
 await testRunner.AndAsync("User looked for value \'BD - Detached\' in \'Type\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
 await testRunner.AndAsync("User looked for value \'B - 1900 - 1918\' in \'Age Code\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
 await testRunner.AndAsync("User enter data for \'Area\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
 await testRunner.AndAsync("User enter data for \'Rooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
 await testRunner.AndAsync("User enter data for \'Bedrooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
 await testRunner.AndAsync("User enter data for \'Bathrooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
 await testRunner.AndAsync("User enter data for \'Floors\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
 await testRunner.AndAsync("User enter data for \'Level\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
 await testRunner.AndAsync("User looked for value \'N - No Conservatory\' in \'Conservatory Type\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
 await testRunner.AndAsync("User looked for value \'G1 - Garaging\' in \'Parking\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
 await testRunner.AndAsync("User clicked on \'Add New Source Code\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
 await testRunner.AndAsync("User looked for \'Source Code\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
 await testRunner.AndAsync("User enter data for \'Comment\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
 await testRunner.AndAsync("User scroll to \'PAD Validation\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
 await testRunner.AndAsync("User click on \'Validate PAD Code\' toggle button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
 await testRunner.AndAsync("user wait till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 93
 await testRunner.AndAsync("User validate value \'Pass\' for \'PAD Validation Outcome\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
 await testRunner.AndAsync("User clicked on \'Check Facts\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 95
 await testRunner.AndAsync("User clicks on \'Is Desktop Research Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 96
 await testRunner.AndAsync("User validates the Pop-ups for \'Borderline NDR to CT\' on the Dekstop Reaserch sta" +
                        "ge", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Researching\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 100
 await testRunner.AndAsync("User waits till \'Undertake Banding\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 101
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Banding\' tab display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 102
 await testRunner.AndAsync("User clicked on \'Banding\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 103
 await testRunner.AndAsync("User enter data for Caseworker Conclusions / Remarks / Thought Process field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
 await testRunner.AndAsync("User looked for \'Proposed Tax Band\' single character field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 105
 await testRunner.AndAsync("User clicks on \'Is Banding Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
 await testRunner.AndAsync("User clicks on \'Confirm and Lock Banding\' button on \'Complete and Lock Banding\' d" +
                        "ialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 107
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 108
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Undertake Banding\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
 await testRunner.AndAsync("User waits till \'Maintain Assessment\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 110
 await testRunner.AndAsync("User closes business process stage container", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 111
 await testRunner.AndAsync("User clicked on \'Assessment\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 112
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 113
 await testRunner.AndAsync("User switchs to Assessment frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
 await testRunner.AndAsync("User clicked on \'Created Assessments\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "Effective_From",
                            "Effective_To",
                            "TaxBand",
                            "CompIndicator",
                            "AssessmentStatus",
                            "PublicationStatus",
                            "AssessmentAction"});
                table21.AddRow(new string[] {
                            "New Proposed Effective Date Updated",
                            "",
                            "Proposed Tax Band",
                            "No",
                            "Current (live entry)",
                            "Unpublished",
                            "New"});
#line 115
 await testRunner.AndAsync("User asserts below \'Created Assessments\' details", ((string)(null)), table21, "And ");
#line hidden
#line 118
 await testRunner.AndAsync("User switchs to deafult frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 119
 await testRunner.AndAsync("User clicked on \'Maintain Assessment\' BPF Journey button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 120
 await testRunner.AndAsync("User clicks on \'Correspondence Checks Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 121
 await testRunner.AndAsync("User clicks on \'Maintain Assessment Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 122
 await testRunner.AndAsync("User clicks on \'Yes\' button on \'Complete Job\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Pending Release\' status dis" +
                        "play", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 126
 await testRunner.AndAsync("User clicked on \'Details\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
 await testRunner.AndAsync("User click on \'Request\' link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 128
 await testRunner.AndAsync("User clicks on \'Release and Publish\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 129
 await testRunner.AndAsync("User clicks on \'OK\' button element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 130
 await testRunner.AndAsync("User closes dialog if still present", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 131
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'List Updated\' status displa" +
                        "y", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 132
 await testRunner.AndAsync("User clicked on \'Assessment\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 133
 await testRunner.AndAsync("User switchs to Assessment frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
 await testRunner.AndAsync("User clicked on \'History\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "Effective_From",
                            "Effective_To",
                            "TaxBand",
                            "CompIndicator",
                            "AssessmentStatus",
                            "PublicationStatus",
                            "AssessmentAction"});
                table22.AddRow(new string[] {
                            "New Proposed Effective Date Updated",
                            "",
                            "Proposed Tax Band",
                            "No",
                            "Current (live entry)",
                            "Published",
                            "New"});
#line 135
 await testRunner.AndAsync("User asserts below \'History\' details", ((string)(null)), table22, "And ");
#line hidden
#line 139
 await testRunner.AndAsync("User clicked on \'Outbound Correspondence\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 140
 await testRunner.AndAsync("User captures correspondence \"Job ID\" in \"featureContext\" by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 141
 await testRunner.AndAsync("User click on correspondence \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 142
 await testRunner.AndAsync("User clicks on \'Status Reason\' dropdown and select \'Ready\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 143
 await testRunner.AndAsync("User clicks on \'OK\' button on \'Outbound Correspondence\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 144
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 145
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 146
 await testRunner.AndAsync("User \'Refresh\' from \'menubar\' until \'Status Reason\' field set to \'Sent\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 147
 await testRunner.AndAsync("User selected \'Integration Messages\' under \'Related\' tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 148
 await testRunner.AndAsync("User click on messages \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 149
 await testRunner.AndAsync("User captures \'Message\' text area field in \'featureContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 150
 await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("NDRtoCT02_BST_135239_CTPRELMGMT-1579 - Borderline NDR to CT Wales - System Genera" +
            "ted Correspondence is created")]
        [global::NUnit.Framework.CategoryAttribute("BorderlineNDRtoCT")]
        [global::NUnit.Framework.CategoryAttribute("E2E")]
        [global::NUnit.Framework.CategoryAttribute("P1_A")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        public async global::System.Threading.Tasks.Task NDRtoCT02_BST_135239_CTPRELMGMT_1579_BorderlineNDRToCTWales_SystemGeneratedCorrespondenceIsCreated()
        {
            string[] tagsOfScenario = new string[] {
                    "BorderlineNDRtoCT",
                    "E2E",
                    "P1_A",
                    "Regression"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("NDRtoCT02_BST_135239_CTPRELMGMT-1579 - Borderline NDR to CT Wales - System Genera" +
                    "ted Correspondence is created", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 154
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 155
 await testRunner.GivenAsync("User uses test data with ID \'NP_002\' from \'Borderline NDR to CT\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 156
 await testRunner.GivenAsync("User is logged in to Dynamics application to work for \"Borderline_NDR to CT_E2E_F" +
                        "low\" case", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 157
 await testRunner.AndAsync("User collapse if site map navigation expanded on left pane", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
 await testRunner.GivenAsync("User click on \'Requests\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 160
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 161
 await testRunner.AndAsync("User looked for \'Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 163
 await testRunner.AndAsync("User entered 0 days before date for \'Date Received\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 164
 await testRunner.AndAsync("User entered 25 days before date for \'Proposed Effective Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 165
 await testRunner.AndAsync("User enter data for \'BA Report Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 166
 await testRunner.AndAsync("User enter data for \'Reason For Validation\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 167
 await testRunner.AndAsync("User looked for \'Submitted By\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 168
 await testRunner.AndAsync("User looked for \'Data Source Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 169
 await testRunner.AndAsync("User clicks on \'Channel\' dropdown and select \'Email\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 171
 await testRunner.AndAsync("User scroll to \'New Hereditament Details\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 172
 await testRunner.AndAsync("User click on \'Find Address\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 173
 await testRunner.AndAsync("user enters data in \"Postcode\" and selects unique address in \'scenarioContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 174
 await testRunner.AndAsync("User enter data for \'Proposed Billing Authority\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 176
 await testRunner.AndAsync("User scroll to \'Billing Authority Link\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 177
 await testRunner.AndAsync("User enter community code number for \"Proposed BA Reference Number\" field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 178
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 179
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 180
 await testRunner.AndAsync("User clicks on \'Validate Request\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 181
 await testRunner.AndAsync("User clicks on \'Proceed\' button on \'Confirm\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 182
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 183
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 184
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 185
 await testRunner.AndAsync("User click on \'Related Jobs\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 186
 await testRunner.AndAsync("User captures \"Job ID\" and \"Job Name\" in \"featureContext\" by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 187
 await testRunner.GivenAsync("User click on \'Jobs\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 188
 await testRunner.AndAsync("User \'Assign\' \'Job Name\' through \'All Jobs\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 189
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 190
    await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 191
 await testRunner.AndAsync("User click on \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 193
 await testRunner.AndAsync("User waits till \'Details\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 194
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Details\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 195
 await testRunner.AndAsync("User waits till \'Researching\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 196
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 197
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 198
 await testRunner.AndAsync("User clicked on \'PVT\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 199
 await testRunner.AndAsync("User clicked on \'Create\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 200
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 202
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 203
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 204
 await testRunner.AndAsync("User looked for value \'19 - Houses and Bungalows\' in \'Group\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 205
 await testRunner.AndAsync("User looked for value \'BD - Detached\' in \'Type\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 206
 await testRunner.AndAsync("User looked for value \'B - 1900 - 1918\' in \'Age Code\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 207
 await testRunner.AndAsync("User enter data for \'Area\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 208
 await testRunner.AndAsync("User enter data for \'Rooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 209
 await testRunner.AndAsync("User enter data for \'Bedrooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 210
 await testRunner.AndAsync("User enter data for \'Bathrooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 211
 await testRunner.AndAsync("User enter data for \'Floors\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 212
 await testRunner.AndAsync("User enter data for \'Level\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 213
 await testRunner.AndAsync("User looked for value \'N - No Conservatory\' in \'Conservatory Type\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 214
 await testRunner.AndAsync("User looked for value \'G1 - Garaging\' in \'Parking\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 215
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 216
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 217
 await testRunner.AndAsync("User clicked on \'Add New Source Code\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 218
 await testRunner.AndAsync("User looked for \'Source Code\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 219
 await testRunner.AndAsync("User enter data for \'Comment\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 220
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 222
 await testRunner.AndAsync("User scroll to \'PAD Validation\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 223
 await testRunner.AndAsync("User click on \'Validate PAD Code\' toggle button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 224
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 225
 await testRunner.AndAsync("user wait till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 226
 await testRunner.AndAsync("User validate value \'Pass\' for \'PAD Validation Outcome\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 227
 await testRunner.AndAsync("User clicked on \'Check Facts\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 228
 await testRunner.AndAsync("User clicks on \'Is Desktop Research Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 229
 await testRunner.AndAsync("User validates the Pop-ups for \'Borderline NDR to CT\' on the Dekstop Reaserch sta" +
                        "ge", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 230
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 231
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 232
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Researching\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 233
 await testRunner.AndAsync("User waits till \'Undertake Banding\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 234
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Banding\' tab display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 235
 await testRunner.AndAsync("User clicked on \'Banding\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 236
 await testRunner.AndAsync("User enter data for Caseworker Conclusions / Remarks / Thought Process field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 237
 await testRunner.AndAsync("User looked for \'Proposed Tax Band\' single character field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 238
 await testRunner.AndAsync("User clicks on \'Is Banding Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 239
 await testRunner.AndAsync("User clicks on \'Confirm and Lock Banding\' button on \'Complete and Lock Banding\' d" +
                        "ialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 240
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 241
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Undertake Banding\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 242
 await testRunner.AndAsync("User waits till \'Maintain Assessment\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 243
 await testRunner.AndAsync("User closes business process stage container", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 244
 await testRunner.AndAsync("User clicked on \'Assessment\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 245
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 246
 await testRunner.AndAsync("User switchs to Assessment frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 247
 await testRunner.AndAsync("User clicked on \'Created Assessments\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "Effective_From",
                            "Effective_To",
                            "TaxBand",
                            "CompIndicator",
                            "AssessmentStatus",
                            "PublicationStatus",
                            "AssessmentAction"});
                table23.AddRow(new string[] {
                            "Proposed Effective Date",
                            "",
                            "Proposed Tax Band",
                            "No",
                            "Current (live entry)",
                            "Unpublished",
                            "New"});
#line 248
 await testRunner.AndAsync("User asserts below \'Created Assessments\' details", ((string)(null)), table23, "And ");
#line hidden
#line 251
 await testRunner.AndAsync("User switchs to deafult frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 252
 await testRunner.AndAsync("User clicked on \'Maintain Assessment\' BPF Journey button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 253
 await testRunner.AndAsync("User clicks on \'Correspondence Checks Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 254
 await testRunner.AndAsync("User clicks on \'Maintain Assessment Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 255
 await testRunner.AndAsync("User clicks on \'Yes\' button on \'Complete Job\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 256
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 257
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 258
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Pending Release\' status dis" +
                        "play", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 259
 await testRunner.AndAsync("User clicked on \'Details\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 260
 await testRunner.AndAsync("User click on \'Request\' link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 261
 await testRunner.AndAsync("User clicks on \'Release and Publish\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 262
 await testRunner.AndAsync("User clicks on \'OK\' button element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 263
 await testRunner.AndAsync("User closes dialog if still present", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 264
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'List Updated\' status displa" +
                        "y", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 265
 await testRunner.AndAsync("User clicked on \'Assessment\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 266
 await testRunner.AndAsync("User switchs to Assessment frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 267
 await testRunner.AndAsync("User clicked on \'History\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "Effective_From",
                            "Effective_To",
                            "TaxBand",
                            "CompIndicator",
                            "AssessmentStatus",
                            "PublicationStatus",
                            "AssessmentAction"});
                table24.AddRow(new string[] {
                            "Proposed Effective Date",
                            "",
                            "Proposed Tax Band",
                            "No",
                            "Current (live entry)",
                            "Published",
                            "New"});
#line 268
 await testRunner.AndAsync("User asserts below \'History\' details", ((string)(null)), table24, "And ");
#line hidden
#line 271
 await testRunner.AndAsync("User switchs to deafult frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 272
 await testRunner.AndAsync("User clicked on \'Outbound Correspondence\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 273
 await testRunner.AndAsync("User captures correspondence \"Job ID\" in \"featureContext\" by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 274
 await testRunner.AndAsync("User click on correspondence \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 275
 await testRunner.AndAsync("User clicks on \'Status Reason\' dropdown and select \'Ready\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 276
 await testRunner.AndAsync("User clicks on \'OK\' button on \'Outbound Correspondence\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 277
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 278
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 279
 await testRunner.AndAsync("User \'Refresh\' from \'menubar\' until \'Status Reason\' field set to \'Sent\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 280
 await testRunner.AndAsync("User selected \'Integration Messages\' under \'Related\' tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 281
 await testRunner.AndAsync("User click on messages \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 282
 await testRunner.AndAsync("User captures \'Message\' text area field in \'featureContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 283
 await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("NDRtoCT03_CTPRELMGMT-1581 - [SIT] - E2E - LA Portal - CR03 - Borderline NDR to CT" +
            "")]
        [global::NUnit.Framework.CategoryAttribute("BorderlineNDRtoCT")]
        [global::NUnit.Framework.CategoryAttribute("E2E")]
        [global::NUnit.Framework.CategoryAttribute("P1_A")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        [global::NUnit.Framework.CategoryAttribute("laportal")]
        public async global::System.Threading.Tasks.Task NDRtoCT03_CTPRELMGMT_1581_SIT_E2E_LAPortal_CR03_BorderlineNDRToCT()
        {
            string[] tagsOfScenario = new string[] {
                    "BorderlineNDRtoCT",
                    "E2E",
                    "P1_A",
                    "Regression",
                    "laportal"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("NDRtoCT03_CTPRELMGMT-1581 - [SIT] - E2E - LA Portal - CR03 - Borderline NDR to CT" +
                    "", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 287
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 288
await testRunner.GivenAsync("User uses test data with ID \'TD_012\' from \'TestDataPart2\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 290
 await testRunner.GivenAsync("User is logged in to LA Portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 291
 await testRunner.WhenAsync("I click Single report tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 292
 await testRunner.ThenAsync("I choose \'CR03\' as the reason code for the submission", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 293
 await testRunner.AndAsync("User enter details on References page for CR03", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 294
 await testRunner.AndAsync("User selects the postcode and Address for the CR03 Portal request", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 295
 await testRunner.AndAsync("User answers the questionnaire about Planning Portal Reference", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 296
 await testRunner.AndAsync("User enter details on Contact Details page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 297
 await testRunner.AndAsync("User enter EFfective Date and Remarks on Change request details page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 298
 await testRunner.ThenAsync("I should be able to see \"You have successfully submitted your report to the Valua" +
                        "tion Office Agency\" message on the screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 299
 await testRunner.GivenAsync("User is logged in", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 300
 await testRunner.AndAsync("User collapse if site map navigation expanded on left pane", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 301
 await testRunner.AndAsync("User navigates to \'Submissions\' under \'Service\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 302
 await testRunner.AndAsync("user waits for \'10\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 303
 await testRunner.AndAsync("User filters the \'Channel\' column with \'Integration\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 304
 await testRunner.AndAsync("User clicks on the latest submission from LA Portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 305
 await testRunner.AndAsync("User validates the field values in Details section under Summary tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 306
 await testRunner.AndAsync("User clicks on the Request link containing the Submission ID under Related Reques" +
                        "ts section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 307
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 308
 await testRunner.AndAsync("User validates the field values in Remarks section under Summary tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 309
 await testRunner.AndAsync("User modified value \'Borderline NDR to CT\' in \'Job Type\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 310
 await testRunner.AndAsync("User scroll to \'New Hereditament Details\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 311
 await testRunner.AndAsync("User click on \'Find Address\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 312
 await testRunner.AndAsync("user enters data in \"Postcode\" and selects unique address in \'scenarioContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 315
 await testRunner.AndAsync("User scroll to \'Billing Authority Link\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 316
 await testRunner.AndAsync("User enter random number for \'Proposed BA Reference Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 317
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 318
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 319
 await testRunner.AndAsync("User clicks on \'Validate Request\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 320
 await testRunner.AndAsync("User clicks on \'Proceed\' button on \'Confirm\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 321
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 322
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 323
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 324
 await testRunner.AndAsync("User click on \'Related Jobs\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 325
 await testRunner.AndAsync("User captures \"Job ID\" and \"Job Name\" in \"featureContext\" by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 326
 await testRunner.GivenAsync("User click on \'Jobs\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 327
 await testRunner.AndAsync("User \'Assign\' \'Job Name\' through \'All Jobs\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 328
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 329
    await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 330
 await testRunner.AndAsync("User click on \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 332
 await testRunner.AndAsync("User waits till \'Details\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 333
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Details\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 334
 await testRunner.AndAsync("User waits till \'Researching\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 335
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 336
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 337
 await testRunner.AndAsync("User clicked on \'PVT\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 338
 await testRunner.AndAsync("User clicked on \'Create\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 339
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 341
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 342
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 343
 await testRunner.AndAsync("User looked for value \'19 - Houses and Bungalows\' in \'Group\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 344
 await testRunner.AndAsync("User looked for value \'BD - Detached\' in \'Type\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 345
 await testRunner.AndAsync("User looked for value \'B - 1900 - 1918\' in \'Age Code\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 346
 await testRunner.AndAsync("User enter data for \'Area\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 347
 await testRunner.AndAsync("User enter data for \'Rooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 348
 await testRunner.AndAsync("User enter data for \'Bedrooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 349
 await testRunner.AndAsync("User enter data for \'Bathrooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 350
 await testRunner.AndAsync("User enter data for \'Floors\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 351
 await testRunner.AndAsync("User enter data for \'Level\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 352
 await testRunner.AndAsync("User looked for value \'N - No Conservatory\' in \'Conservatory Type\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 353
 await testRunner.AndAsync("User looked for value \'G1 - Garaging\' in \'Parking\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 354
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 355
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 357
 await testRunner.AndAsync("User clicked on \'Add New Source Code\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 358
 await testRunner.AndAsync("User looked for \'Source Code\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 359
 await testRunner.AndAsync("User enter data for \'Comment\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 360
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 362
 await testRunner.AndAsync("User scroll to \'PAD Validation\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 363
 await testRunner.AndAsync("User click on \'Validate PAD Code\' toggle button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 364
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 365
 await testRunner.AndAsync("user wait till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 366
 await testRunner.AndAsync("User validate value \'Pass\' for \'PAD Validation Outcome\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 367
 await testRunner.AndAsync("User clicked on \'Check Facts\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 368
 await testRunner.AndAsync("User clicks on \'Is Desktop Research Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 369
 await testRunner.AndAsync("User validates the Pop-ups for \'Borderline NDR to CT\' on the Dekstop Reaserch sta" +
                        "ge", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 370
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 371
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 372
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Researching\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 373
 await testRunner.AndAsync("User waits till \'Undertake Banding\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 374
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Banding\' tab display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 375
 await testRunner.AndAsync("User clicked on \'Banding\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 376
 await testRunner.AndAsync("User enter data for Caseworker Conclusions / Remarks / Thought Process field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 377
 await testRunner.AndAsync("User looked for \'Proposed Tax Band\' single character field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 378
 await testRunner.AndAsync("User clicks on \'Is Banding Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 379
 await testRunner.AndAsync("User clicks on \'Confirm and Lock Banding\' button on \'Complete and Lock Banding\' d" +
                        "ialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 380
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 381
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Undertake Banding\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 382
 await testRunner.AndAsync("User waits till \'Maintain Assessment\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 383
 await testRunner.AndAsync("User closes business process stage container", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 384
 await testRunner.AndAsync("User clicked on \'Assessment\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 385
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 386
 await testRunner.AndAsync("User clicked on \'Maintain Assessment\' BPF Journey button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 387
 await testRunner.AndAsync("User clicks on \'Correspondence Checks Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 388
 await testRunner.AndAsync("User clicks on \'Maintain Assessment Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 389
 await testRunner.AndAsync("User clicks on \'Yes\' button on \'Complete Job\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 390
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 391
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 392
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Pending Release\' status dis" +
                        "play", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 393
 await testRunner.AndAsync("User clicked on \'Details\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 394
 await testRunner.AndAsync("User click on \'Request\' link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 395
 await testRunner.AndAsync("User clicks on \'Release and Publish\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 396
 await testRunner.AndAsync("User clicks on \'OK\' button element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 397
 await testRunner.AndAsync("User closes dialog if still present", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 398
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'List Updated\' status displa" +
                        "y", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 399
 await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
