// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace POMSeleniumFrameworkPoc1.Features.UI.E2E
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("ChangeOfBAReference")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("UI")]
    public partial class ChangeOfBAReferenceFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "UI"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/UI/E2E", "ChangeOfBAReference", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "ChangeOfBAReference.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/UI/E2E/ChangeOfBAReference.feature", 7);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("BAREF01_CTPRELMGMT-1673_CTPRELMGMT-1437_CTPRELMGMT-1450_BAref_Change of BA refere" +
            "nce Manual Process -Current Date")]
        [global::NUnit.Framework.CategoryAttribute("ChangeofBAReference")]
        [global::NUnit.Framework.CategoryAttribute("E2E")]
        [global::NUnit.Framework.CategoryAttribute("P1_A")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        [global::NUnit.Framework.CategoryAttribute("mini_Regression")]
        [global::NUnit.Framework.CategoryAttribute("HP_E2E")]
        public async global::System.Threading.Tasks.Task BAREF01_CTPRELMGMT_1673_CTPRELMGMT_1437_CTPRELMGMT_1450_BAref_ChangeOfBAReferenceManualProcess_CurrentDate()
        {
            string[] tagsOfScenario = new string[] {
                    "ChangeofBAReference",
                    "E2E",
                    "P1_A",
                    "Regression",
                    "mini_Regression",
                    "HP_E2E"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BAREF01_CTPRELMGMT-1673_CTPRELMGMT-1437_CTPRELMGMT-1450_BAref_Change of BA refere" +
                    "nce Manual Process -Current Date", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
 await testRunner.GivenAsync("User uses test data with ID \'BAR_003\' from \'BAref\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table43 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table43.AddRow(new string[] {
                            "town"});
                table43.AddRow(new string[] {
                            "postcode"});
                table43.AddRow(new string[] {
                            "uprn"});
                table43.AddRow(new string[] {
                            "effective_from_date"});
                table43.AddRow(new string[] {
                            "ba_reference"});
#line 10
 await testRunner.AndAsync("User connects to the DB and retrieves the data for \'findHereditament_Rugby_BAREF\'" +
                        "", ((string)(null)), table43, "And ");
#line hidden
#line 17
 await testRunner.GivenAsync("User is logged in to Dynamics application to work for \"E2E_Manual process BA refe" +
                        "rence\" case", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
 await testRunner.AndAsync("User collapse if site map navigation expanded on left pane", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.GivenAsync("User click on \'Requests\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
 await testRunner.AndAsync("User looked for \'Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
 await testRunner.AndAsync("User looked for \'Submitted By\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
 await testRunner.AndAsync("User entered 0 days before date for \'Date Received\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
 await testRunner.AndAsync("User enters \'0\' days after hereditament \'effective_from_date\' for \'Proposed Effec" +
                        "tive Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
 await testRunner.AndAsync("User looked for \'Data Source Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
 await testRunner.AndAsync("User clicks on \'Channel\' dropdown and select \'Email\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
 await testRunner.AndAsync("User enter data for \'BA Report Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
 await testRunner.AndAsync("User enter data for \'Reason For Validation\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
 await testRunner.AndAsync("User click on \'Find Hereditament\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
 await testRunner.AndAsync("User select \'UPRN\' value from \'Search By\' dropdown", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
 await testRunner.AndAsync("User enters data in \"UPRN\" field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
 await testRunner.AndAsync("User clicked on \'Search\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
 await testRunner.AndAsync("User slects spcific \'uprn\' row from search hereditament results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
 await testRunner.AndAsync("User clicked on \'Select\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
 await testRunner.AndAsync("User waits till Find Hereditament dialog disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
 await testRunner.AndAsync("User clicks on \'Swap BA Reference Number?\' dropdown and select \'No\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
 await testRunner.AndAsync("User enter random number for \'Proposed BA Reference Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
 await testRunner.AndAsync("User clicks on \'Validate Request\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
 await testRunner.AndAsync("User waits till \'dialog\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
 await testRunner.AndAsync("User click on \'BA Reference\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
 await testRunner.AndAsync("User click on \'New Proposed BA Reference\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
 await testRunner.AndAsync("User click on \'Related Jobs\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
 await testRunner.AndAsync("User captures \"Job ID\" and \"Job Name\" in \"featureContext\" by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
 await testRunner.GivenAsync("User click on \'Jobs\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 53
 await testRunner.AndAsync("User \'Assign\' \'Job Name\' through \'All Jobs\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
    await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
 await testRunner.AndAsync("User click on \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
 await testRunner.AndAsync("User waits till \'Details\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Details\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
 await testRunner.AndAsync("User click on \'Unlock Stage\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
 await testRunner.AndAsync("User selects \'Change Proposed Effective Date\' from \'unlockjobstage\' this dropdown" +
                        " and validate value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
 await testRunner.AndAsync("User clicked on \'Confirm\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
 await testRunner.AndAsync("user waits till \'Unlock Stage is in progress\' icon disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
 await testRunner.AndAsync("user waits for \'30\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
 await testRunner.AndAsync("User waits till \'Researching\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
 await testRunner.AndAsync("User clicked on \'BA Reference\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
 await testRunner.AndAsync("User clicks on \'Validate for Release\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
 await testRunner.AndAsync("User clicks on \'Yes\' button on \'Complete Job\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
 await testRunner.AndAsync("User click on job link in Header", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Pending Release\' status dis" +
                        "play", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
 await testRunner.AndAsync("User clicked on \'Details\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
 await testRunner.AndAsync("User click on \'Request\' link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
 await testRunner.AndAsync("User clicks on \'Release and Publish\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
 await testRunner.AndAsync("User clicks on \'OK\' button element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
 await testRunner.AndAsync("User closes dialog if still present", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Resolved\' status display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
 await testRunner.AndAsync("User clicked on \'Details\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
 await testRunner.AndAsync("User scroll to \'Hereditament Details\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
 await testRunner.AndAsync("User click on \'Hereditament\' link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
 await testRunner.AndAsync("User selects the \'Billing Authority Links\' from the \'Related\' tab from \'Hereditam" +
                        "ent Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table44 = new global::Reqnroll.Table(new string[] {
                            "Billing_Authority",
                            "BA_Reference",
                            "Effective_From",
                            "Effective_To",
                            "Status"});
                table44.AddRow(new string[] {
                            "Submitted By",
                            "Proposed BA Reference Number",
                            "Proposed Effective Date",
                            "",
                            "Committed"});
                table44.AddRow(new string[] {
                            "Submitted By",
                            "ba_reference",
                            "effective_from_date",
                            "Proposed Effective Date",
                            "Superseded"});
#line 84
 await testRunner.AndAsync("User asserts below \'Billing Authority Links\' details and validate effetive to dat" +
                        "e", ((string)(null)), table44, "And ");
#line hidden
#line 88
 await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("BAREF02_CTPRELMGMT-1670_BAref_Change of BA reference Auto Process  Current")]
        [global::NUnit.Framework.CategoryAttribute("ChangeofBAReference")]
        [global::NUnit.Framework.CategoryAttribute("E2E")]
        [global::NUnit.Framework.CategoryAttribute("P1_A")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        public async global::System.Threading.Tasks.Task BAREF02_CTPRELMGMT_1670_BAref_ChangeOfBAReferenceAutoProcessCurrent()
        {
            string[] tagsOfScenario = new string[] {
                    "ChangeofBAReference",
                    "E2E",
                    "P1_A",
                    "Regression"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BAREF02_CTPRELMGMT-1670_BAref_Change of BA reference Auto Process  Current", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 91
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 92
 await testRunner.GivenAsync("User uses test data with ID \'BAR_003\' from \'BAref\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table45 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table45.AddRow(new string[] {
                            "town"});
                table45.AddRow(new string[] {
                            "postcode"});
                table45.AddRow(new string[] {
                            "uprn"});
                table45.AddRow(new string[] {
                            "effective_from_date"});
                table45.AddRow(new string[] {
                            "ba_reference"});
#line 93
 await testRunner.AndAsync("User connects to the DB and retrieves the data for \'findHereditament_Rugby_BAREF\'" +
                        "", ((string)(null)), table45, "And ");
#line hidden
#line 100
 await testRunner.GivenAsync("User is logged in to Dynamics application to work for \"E2E_Auto process BA refere" +
                        "nce\" case", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 101
 await testRunner.AndAsync("User collapse if site map navigation expanded on left pane", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 102
 await testRunner.GivenAsync("User click on \'Requests\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 103
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
 await testRunner.AndAsync("User looked for \'Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 105
 await testRunner.AndAsync("User looked for \'Submitted By\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 107
 await testRunner.AndAsync("User entered 0 days before date for \'Date Received\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 108
 await testRunner.AndAsync("User enters \'0\' days after hereditament \'effective_from_date\' for \'Proposed Effec" +
                        "tive Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
 await testRunner.AndAsync("User looked for \'Data Source Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 110
 await testRunner.AndAsync("User clicks on \'Channel\' dropdown and select \'Email\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 111
 await testRunner.AndAsync("User enter data for \'BA Report Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 112
 await testRunner.AndAsync("User enter data for \'Reason For Validation\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 113
 await testRunner.AndAsync("User click on \'Find Hereditament\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
 await testRunner.AndAsync("User select \'UPRN\' value from \'Search By\' dropdown", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 115
 await testRunner.AndAsync("User enters data in \"UPRN\" field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
 await testRunner.AndAsync("User clicked on \'Search\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 117
 await testRunner.AndAsync("User slects spcific \'uprn\' row from search hereditament results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 118
 await testRunner.AndAsync("User clicked on \'Select\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 119
 await testRunner.AndAsync("User waits till Find Hereditament dialog disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 120
 await testRunner.AndAsync("User enter random number for \'Proposed BA Reference Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 121
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 122
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
 await testRunner.AndAsync("User clicks on \'Validate Request\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
 await testRunner.AndAsync("User waits till \'dialog\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 126
 await testRunner.AndAsync("User click on \'BA Reference\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
 await testRunner.AndAsync("User click on \'New Proposed BA Reference Amendment\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 128
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 129
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 130
 await testRunner.AndAsync("User clicks on \'Validate For Autoprocess\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 131
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 132
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 133
 await testRunner.AndAsync("User click on \'Related Jobs\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
 await testRunner.AndAsync("User captures \"Job ID\" and \"Job Name\" in \"featureContext\" by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 138
 await testRunner.GivenAsync("User click on \'Jobs\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 139
 await testRunner.AndAsync("User \'Assign\' \'Job Name\' through \'All Jobs\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 140
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 141
    await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 142
 await testRunner.AndAsync("User click on \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 143
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Resolved\' status display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 144
 await testRunner.AndAsync("User clicked on \'Details\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 145
 await testRunner.AndAsync("User scroll to \'Hereditament Details\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 146
 await testRunner.AndAsync("User click on \'Hereditament\' link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 147
 await testRunner.AndAsync("User selects the \'Billing Authority Links\' from the \'Related\' tab from \'Hereditam" +
                        "ent Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table46 = new global::Reqnroll.Table(new string[] {
                            "Billing_Authority",
                            "BA_Reference",
                            "Effective_From",
                            "Effective_To",
                            "Status"});
                table46.AddRow(new string[] {
                            "Submitted By",
                            "Proposed BA Reference Number",
                            "Proposed Effective Date",
                            "",
                            "Committed"});
                table46.AddRow(new string[] {
                            "Submitted By",
                            "ba_reference",
                            "effective_from_date",
                            "Proposed Effective Date",
                            "Superseded"});
#line 148
 await testRunner.AndAsync("User asserts below \'Billing Authority Links\' details", ((string)(null)), table46, "And ");
#line hidden
#line 152
 await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("BAREF03_CTPRELMGMT-1424_[WAR-1035] Valid BA Reference Number for swap within Bill" +
            "ing Authority of selected Hereditament and verify Autoprocess resolved the jobs")]
        [global::NUnit.Framework.CategoryAttribute("ChangeofBAReference")]
        [global::NUnit.Framework.CategoryAttribute("E2E")]
        [global::NUnit.Framework.CategoryAttribute("P1_B")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        [global::NUnit.Framework.CategoryAttribute("HP_E2E")]
        public async global::System.Threading.Tasks.Task BAREF03_CTPRELMGMT_1424_WAR_1035ValidBAReferenceNumberForSwapWithinBillingAuthorityOfSelectedHereditamentAndVerifyAutoprocessResolvedTheJobs()
        {
            string[] tagsOfScenario = new string[] {
                    "ChangeofBAReference",
                    "E2E",
                    "P1_B",
                    "Regression",
                    "HP_E2E"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BAREF03_CTPRELMGMT-1424_[WAR-1035] Valid BA Reference Number for swap within Bill" +
                    "ing Authority of selected Hereditament and verify Autoprocess resolved the jobs", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 157
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 158
 await testRunner.GivenAsync("User uses test data with ID \'BAR_005\' from \'BAref\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table47 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table47.AddRow(new string[] {
                            "town"});
                table47.AddRow(new string[] {
                            "postcode"});
                table47.AddRow(new string[] {
                            "uprn"});
                table47.AddRow(new string[] {
                            "effective_from_date"});
                table47.AddRow(new string[] {
                            "ba_reference"});
#line 159
 await testRunner.AndAsync("User connects to the DB and retrieves the \'1\' set of data for \'findHereditament_h" +
                        "illingdon_BAREF\'", ((string)(null)), table47, "And ");
#line hidden
                global::Reqnroll.Table table48 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table48.AddRow(new string[] {
                            "town"});
                table48.AddRow(new string[] {
                            "postcode"});
                table48.AddRow(new string[] {
                            "uprn"});
                table48.AddRow(new string[] {
                            "effective_from_date"});
                table48.AddRow(new string[] {
                            "ba_reference"});
#line 167
 await testRunner.AndAsync("User connects to the DB and retrieves the \'2\' set of data for \'findHereditament_h" +
                        "illingdon_BAREF\'", ((string)(null)), table48, "And ");
#line hidden
#line 174
 await testRunner.GivenAsync("User is logged in to Dynamics application to work for \"BA Reference Swap Heredita" +
                        "ment\" case", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 175
 await testRunner.AndAsync("User collapse if site map navigation expanded on left pane", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 176
 await testRunner.GivenAsync("User click on \'Requests\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 177
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 178
 await testRunner.AndAsync("User looked for \'Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 179
 await testRunner.AndAsync("User looked for \'Submitted By\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 180
 await testRunner.AndAsync("User entered 0 days before date for \'Date Received\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 181
 await testRunner.AndAsync("User enters \'2\' days after hereditament \'effective_from_date\' for \'Proposed Effec" +
                        "tive Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 182
 await testRunner.AndAsync("User looked for \'Data Source Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 183
 await testRunner.AndAsync("User clicks on \'Channel\' dropdown and select \'Email\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 184
 await testRunner.AndAsync("User enter data for \'BA Report Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 185
 await testRunner.AndAsync("User enter data for \'Reason For Validation\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 186
 await testRunner.AndAsync("User click on \'Find Hereditament\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 187
 await testRunner.AndAsync("User select \'UPRN\' value from \'Search By\' dropdown", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 188
 await testRunner.AndAsync("User enters data in \"UPRN\" field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 189
 await testRunner.AndAsync("User clicked on \'Search\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 190
 await testRunner.AndAsync("User slects spcific \'uprn\' row from search hereditament results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 191
 await testRunner.AndAsync("User clicked on \'Select\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 192
 await testRunner.AndAsync("User waits till Find Hereditament dialog disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 193
 await testRunner.AndAsync("User clicks on \'Swap BA Reference Number?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 194
 await testRunner.AndAsync("User enter swap heriditament BA ref number for \'Proposed BA Reference Number\' fie" +
                        "ld value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 195
 await testRunner.AndAsync("User click on \'Billing Authority Link\' label", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 196
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 197
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 198
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 199
 await testRunner.AndAsync("User clicks on \'Validate Request\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 202
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 203
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 204
 await testRunner.AndAsync("User fetch \'CBR_Request\' in \'featureContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 206
 await testRunner.AndAsync("User clicks on \'Supplementary Job Requisition\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 207
 await testRunner.AndAsync("User looked for \'Job Type\' field value from \'TestDataPart3\' for \'PAA_002\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 208
 await testRunner.AndAsync("User click on \'Find Hereditament\' button on \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 209
 await testRunner.AndAsync("User enters data in \"Postcode_new\" field for swap heriditament", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 210
 await testRunner.AndAsync("User clicked on \'Search\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 211
 await testRunner.AndAsync("User slects spcific \'uprn_new\' row from search hereditament results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 212
 await testRunner.AndAsync("User clicked on \'Select\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 213
 await testRunner.AndAsync("user waits for \'5\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 214
 await testRunner.AndAsync("User waits till Find Hereditament dialog disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 215
 await testRunner.AndAsync("User enters second heraditament  BA ref number for \'Proposed BA Reference Number\'" +
                        " field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 216
 await testRunner.AndAsync("User click on \'Save\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 217
 await testRunner.AndAsync("user waits till \'Saving...\' disappears on dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 218
 await testRunner.AndAsync("User click on \'Submit\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 219
 await testRunner.AndAsync("User clicks on \'Continue\' button on \'Confirm Supplementary Job Requisition\' dialo" +
                        "g", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 220
 await testRunner.AndAsync("user waits till \'Saving...\' disappears on dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 221
 await testRunner.AndAsync("User closes dialog if still present", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 222
 await testRunner.AndAsync("User click on \'Related Jobs\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 223
 await testRunner.AndAsync("user asserts related jobs row count \'2\' by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 224
 await testRunner.AndAsync("User waits till all 2 jobs has name displayed by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 226
 await testRunner.AndAsync("User captured all 2 recons \"Job ID\" and \"Job Name\" in \"featureContext\" by \"Refres" +
                        "h\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 227
 await testRunner.AndAsync("User click on \'BA Reference\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 228
 await testRunner.AndAsync("User click on \'New Proposed BA Reference Amendment\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 229
 await testRunner.AndAsync("User scroll to \'Swap Hereditament\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 230
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 231
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 232
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 233
 await testRunner.AndAsync("User click on \'BA Reference\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 234
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 235
 await testRunner.AndAsync("user asserts Proposed BA Reference Amendments  row count \'2\' by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 236
 await testRunner.AndAsync("User clicks on \'Validate For Autoprocess\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 237
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 238
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 239
 await testRunner.GivenAsync("User click on \'Jobs\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 241
 await testRunner.AndAsync("User \'Assign\' \'Job_0\' \'Job Name\' through \'All Jobs\' for Reconstitution", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 242
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 243
    await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 244
 await testRunner.AndAsync("User click on \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 245
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Resolved\' status display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 246
 await testRunner.AndAsync("User clicked on \'Details\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 247
 await testRunner.AndAsync("User scroll to \'Hereditament Details\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 248
 await testRunner.AndAsync("User click on \'Hereditament\' link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 249
 await testRunner.AndAsync("User selects the \'Billing Authority Links\' from the \'Related\' tab from \'Hereditam" +
                        "ent Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table49 = new global::Reqnroll.Table(new string[] {
                            "Billing_Authority",
                            "BA_Reference",
                            "Effective_From",
                            "Effective_To",
                            "Status"});
                table49.AddRow(new string[] {
                            "Submitted By",
                            "ba_reference",
                            "Proposed Effective Date",
                            "",
                            "Committed"});
                table49.AddRow(new string[] {
                            "Submitted By",
                            "ba_reference_new",
                            "effective_from_date_new",
                            "Proposed Effective Date",
                            "Committed"});
#line 250
 await testRunner.AndAsync("User asserts below \'Billing Authority Links\' details", ((string)(null)), table49, "And ");
#line hidden
#line 254
 await testRunner.GivenAsync("User click on \'Jobs\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 255
 await testRunner.AndAsync("User clicks on \'OK\' button on \'Leave this page?\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 256
 await testRunner.AndAsync("User \'Assign\' \'Job_1\' \'Job Name\' through \'All Jobs\' for Reconstitution", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 257
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 258
    await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 259
 await testRunner.AndAsync("User click on \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 260
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Resolved\' status display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 261
 await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("BAREF04_CTPRELMGMT-1424 [WAR-1035] Valid BA Reference Number for swap within Bill" +
            "ing Authority of selected Hereditament and verify Autoprocess resolved the jobs")]
        [global::NUnit.Framework.CategoryAttribute("ChangeofBAReference")]
        [global::NUnit.Framework.CategoryAttribute("E2E")]
        [global::NUnit.Framework.CategoryAttribute("P1_B")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        public async global::System.Threading.Tasks.Task BAREF04_CTPRELMGMT_1424WAR_1035ValidBAReferenceNumberForSwapWithinBillingAuthorityOfSelectedHereditamentAndVerifyAutoprocessResolvedTheJobs()
        {
            string[] tagsOfScenario = new string[] {
                    "ChangeofBAReference",
                    "E2E",
                    "P1_B",
                    "Regression"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BAREF04_CTPRELMGMT-1424 [WAR-1035] Valid BA Reference Number for swap within Bill" +
                    "ing Authority of selected Hereditament and verify Autoprocess resolved the jobs", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 266
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 267
 await testRunner.GivenAsync("User uses test data with ID \'BAR_006\' from \'BAref\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table50 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table50.AddRow(new string[] {
                            "town"});
                table50.AddRow(new string[] {
                            "postcode"});
                table50.AddRow(new string[] {
                            "uprn"});
                table50.AddRow(new string[] {
                            "effective_from_date"});
                table50.AddRow(new string[] {
                            "ba_reference"});
#line 268
 await testRunner.AndAsync("User connects to the DB and retrieves the \'1\' set of data for \'findHereditament_s" +
                        "wansea_BAREF\'", ((string)(null)), table50, "And ");
#line hidden
                global::Reqnroll.Table table51 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table51.AddRow(new string[] {
                            "town"});
                table51.AddRow(new string[] {
                            "postcode"});
                table51.AddRow(new string[] {
                            "uprn"});
                table51.AddRow(new string[] {
                            "effective_from_date"});
                table51.AddRow(new string[] {
                            "ba_reference"});
#line 276
 await testRunner.AndAsync("User connects to the DB and retrieves the \'2\' set of data for \'findHereditament_s" +
                        "wansea_BAREF\'", ((string)(null)), table51, "And ");
#line hidden
#line 283
 await testRunner.GivenAsync("User is logged in to Dynamics application to work for \"BA Reference Swap Heredita" +
                        "ment_wales\" case", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 284
 await testRunner.AndAsync("User collapse if site map navigation expanded on left pane", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 285
 await testRunner.GivenAsync("User click on \'Requests\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 286
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 287
 await testRunner.AndAsync("User looked for \'Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 288
 await testRunner.AndAsync("User looked for \'Submitted By\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 289
 await testRunner.AndAsync("User entered 0 days before date for \'Date Received\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 290
 await testRunner.AndAsync("User enters \'2\' days after hereditament \'effective_from_date\' for \'Proposed Effec" +
                        "tive Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 291
 await testRunner.AndAsync("User looked for \'Data Source Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 292
 await testRunner.AndAsync("User clicks on \'Channel\' dropdown and select \'Email\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 293
 await testRunner.AndAsync("User enter data for \'BA Report Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 294
 await testRunner.AndAsync("User enter data for \'Reason For Validation\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 295
 await testRunner.AndAsync("User click on \'Find Hereditament\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 296
 await testRunner.AndAsync("User select \'UPRN\' value from \'Search By\' dropdown", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 297
 await testRunner.AndAsync("User enters data in \"UPRN\" field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 298
 await testRunner.AndAsync("User clicked on \'Search\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 299
 await testRunner.AndAsync("User slects spcific \'uprn\' row from search hereditament results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 300
 await testRunner.AndAsync("User clicked on \'Select\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 301
 await testRunner.AndAsync("User waits till Find Hereditament dialog disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 302
 await testRunner.AndAsync("User clicks on \'Swap BA Reference Number?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 303
 await testRunner.AndAsync("User enter swap heriditament BA ref number for \'Proposed BA Reference Number\' fie" +
                        "ld value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 304
 await testRunner.AndAsync("User click on \'Billing Authority Link\' label", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 305
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 306
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 307
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 308
 await testRunner.AndAsync("User clicks on \'Validate Request\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 311
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 312
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 313
 await testRunner.AndAsync("User fetch \'CBR_Request\' in \'featureContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 315
 await testRunner.AndAsync("User clicks on \'Supplementary Job Requisition\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 316
 await testRunner.AndAsync("User looked for \'Job Type\' field value from \'TestDataPart3\' for \'PAA_002\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 317
 await testRunner.AndAsync("User click on \'Find Hereditament\' button on \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 318
 await testRunner.AndAsync("User enters data in \"Postcode_new\" field for swap heriditament", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 319
 await testRunner.AndAsync("User clicked on \'Search\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 320
 await testRunner.AndAsync("User slects spcific \'uprn_new\' row from search hereditament results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 321
 await testRunner.AndAsync("User clicked on \'Select\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 322
 await testRunner.AndAsync("user waits for \'5\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 323
 await testRunner.AndAsync("User waits till Find Hereditament dialog disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 324
 await testRunner.AndAsync("User enters second heraditament  BA ref number for \'Proposed BA Reference Number\'" +
                        " field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 325
 await testRunner.AndAsync("User click on \'Save\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 326
 await testRunner.AndAsync("user waits till \'Saving...\' disappears on dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 327
 await testRunner.AndAsync("User click on \'Submit\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 328
 await testRunner.AndAsync("User clicks on \'Continue\' button on \'Confirm Supplementary Job Requisition\' dialo" +
                        "g", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 329
 await testRunner.AndAsync("user waits till \'Saving...\' disappears on dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 330
 await testRunner.AndAsync("User closes dialog if still present", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 331
 await testRunner.AndAsync("User click on \'Related Jobs\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 332
 await testRunner.AndAsync("user asserts related jobs row count \'2\' by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 333
 await testRunner.AndAsync("User waits till all 2 jobs has name displayed by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 335
 await testRunner.AndAsync("User captured all 2 recons \"Job ID\" and \"Job Name\" in \"featureContext\" by \"Refres" +
                        "h\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 336
 await testRunner.AndAsync("User click on \'BA Reference\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 337
 await testRunner.AndAsync("User click on \'New Proposed BA Reference Amendment\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 338
 await testRunner.AndAsync("User scroll to \'Swap Hereditament\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 339
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 340
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 341
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 342
 await testRunner.AndAsync("User click on \'BA Reference\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 343
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 344
 await testRunner.AndAsync("user asserts Proposed BA Reference Amendments  row count \'2\' by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 345
 await testRunner.AndAsync("User clicks on \'Validate For Autoprocess\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 346
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 347
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 348
 await testRunner.GivenAsync("User click on \'Jobs\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 350
 await testRunner.AndAsync("User \'Assign\' \'Job_0\' \'Job Name\' through \'All Jobs\' for Reconstitution", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 351
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 352
    await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 353
 await testRunner.AndAsync("User click on \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 354
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Resolved\' status display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 355
 await testRunner.AndAsync("User clicked on \'Details\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 356
 await testRunner.AndAsync("User scroll to \'Hereditament Details\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 357
 await testRunner.AndAsync("User click on \'Hereditament\' link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 358
 await testRunner.AndAsync("User selects the \'Billing Authority Links\' from the \'Related\' tab from \'Hereditam" +
                        "ent Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table52 = new global::Reqnroll.Table(new string[] {
                            "Billing_Authority",
                            "BA_Reference",
                            "Effective_From",
                            "Effective_To",
                            "Status"});
                table52.AddRow(new string[] {
                            "Submitted By",
                            "ba_reference",
                            "Proposed Effective Date",
                            "",
                            "Committed"});
                table52.AddRow(new string[] {
                            "Submitted By",
                            "ba_reference_new",
                            "effective_from_date_new",
                            "Proposed Effective Date",
                            "Committed"});
#line 359
 await testRunner.AndAsync("User asserts below \'Billing Authority Links\' details", ((string)(null)), table52, "And ");
#line hidden
#line 363
 await testRunner.GivenAsync("User click on \'Jobs\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 364
 await testRunner.AndAsync("User clicks on \'OK\' button on \'Leave this page?\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 365
 await testRunner.AndAsync("User \'Assign\' \'Job_1\' \'Job Name\' through \'All Jobs\' for Reconstitution", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 366
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 367
    await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 368
 await testRunner.AndAsync("User click on \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 369
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Resolved\' status display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 370
 await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("BAREF05_CTPRELMGMT-1427__CTPRELMGMT-1423_[SIT] - [WAR-1035] Invalid BA reference " +
            "check and Guardrail validation rules for Swap process- Proposed BA Reference Num" +
            "ber is matching with BA reference number of selected hereditament")]
        [global::NUnit.Framework.CategoryAttribute("ChangeofBAReference")]
        [global::NUnit.Framework.CategoryAttribute("E2E")]
        [global::NUnit.Framework.CategoryAttribute("P2")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        public async global::System.Threading.Tasks.Task BAREF05_CTPRELMGMT_1427__CTPRELMGMT_1423_SIT_WAR_1035InvalidBAReferenceCheckAndGuardrailValidationRulesForSwapProcess_ProposedBAReferenceNumberIsMatchingWithBAReferenceNumberOfSelectedHereditament()
        {
            string[] tagsOfScenario = new string[] {
                    "ChangeofBAReference",
                    "E2E",
                    "P2",
                    "Regression"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BAREF05_CTPRELMGMT-1427__CTPRELMGMT-1423_[SIT] - [WAR-1035] Invalid BA reference " +
                    "check and Guardrail validation rules for Swap process- Proposed BA Reference Num" +
                    "ber is matching with BA reference number of selected hereditament", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 375
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 376
 await testRunner.GivenAsync("User uses test data with ID \'BAR_007\' from \'BAref\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table53 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table53.AddRow(new string[] {
                            "town"});
                table53.AddRow(new string[] {
                            "postcode"});
                table53.AddRow(new string[] {
                            "uprn"});
                table53.AddRow(new string[] {
                            "effective_from_date"});
                table53.AddRow(new string[] {
                            "ba_reference"});
#line 377
 await testRunner.AndAsync("User connects to the DB and retrieves the \'1\' set of data for \'findHereditament_c" +
                        "anterbury_BAREF\'", ((string)(null)), table53, "And ");
#line hidden
                global::Reqnroll.Table table54 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table54.AddRow(new string[] {
                            "town"});
                table54.AddRow(new string[] {
                            "postcode"});
                table54.AddRow(new string[] {
                            "uprn"});
                table54.AddRow(new string[] {
                            "effective_from_date"});
                table54.AddRow(new string[] {
                            "ba_reference"});
#line 385
 await testRunner.AndAsync("User connects to the DB and retrieves the \'2\' set of data for \'findHereditament_c" +
                        "anterbury_BAREF\'", ((string)(null)), table54, "And ");
#line hidden
#line 392
 await testRunner.GivenAsync("User is logged in to Dynamics application to work for \"BA Reference _Invalid_Guar" +
                        "drails\" case", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 393
 await testRunner.AndAsync("User collapse if site map navigation expanded on left pane", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 394
 await testRunner.GivenAsync("User click on \'Requests\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 395
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 396
 await testRunner.AndAsync("User looked for \'Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 397
 await testRunner.AndAsync("User looked for \'Submitted By\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 398
 await testRunner.AndAsync("User entered 0 days before date for \'Date Received\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 399
 await testRunner.AndAsync("User enters \'2\' days after hereditament \'effective_from_date\' for \'Proposed Effec" +
                        "tive Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 400
 await testRunner.AndAsync("User looked for \'Data Source Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 401
 await testRunner.AndAsync("User clicks on \'Channel\' dropdown and select \'Email\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 402
 await testRunner.AndAsync("User enter data for \'BA Report Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 403
 await testRunner.AndAsync("User enter data for \'Reason For Validation\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 404
 await testRunner.AndAsync("User click on \'Find Hereditament\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 405
 await testRunner.AndAsync("User select \'UPRN\' value from \'Search By\' dropdown", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 406
 await testRunner.AndAsync("User enters data in \"UPRN\" field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 407
 await testRunner.AndAsync("User clicked on \'Search\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 408
 await testRunner.AndAsync("User slects spcific \'uprn\' row from search hereditament results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 409
 await testRunner.AndAsync("User clicked on \'Select\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 410
 await testRunner.AndAsync("User waits till Find Hereditament dialog disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 411
 await testRunner.AndAsync("User clicks on \'Swap BA Reference Number?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 412
 await testRunner.AndAsync("User enter same hereditament BA ref number for \'Proposed BA Reference Number\' fie" +
                        "ld value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 413
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 415
 await testRunner.AndAsync("User verifies \'Proposed BA Reference Number : Invalid value of BA Reference Numbe" +
                        "r. To swap a BA Reference number the proposed BA Reference Number must match wit" +
                        "h existing hereditament\' Banner message", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 416
 await testRunner.AndAsync("User entered random number for \'Proposed BA Reference Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 417
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 418
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 419
 await testRunner.AndAsync("User verifies \'Proposed BA Reference Number : Invalid value of BA Reference Numbe" +
                        "r. To swap a BA Reference number the proposed BA Reference Number must match wit" +
                        "h existing hereditament\' Banner message", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 420
 await testRunner.AndAsync("User clicks on \'Swap BA Reference Number?\' dropdown and select \'No\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 421
 await testRunner.AndAsync("User enter swap heriditament BA ref number for \'Proposed BA Reference Number\' fie" +
                        "ld value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 422
 await testRunner.AndAsync("User clicks on \'Swap BA Reference Number?\' dropdown and select \'No\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 423
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 424
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 425
 await testRunner.AndAsync("User verifies \'Proposed BA Reference Number : Value of Proposed BA Reference Numb" +
                        "er is in use. BA Reference Number must be unique within proposed billing authori" +
                        "ty.\' Banner message", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 426
 await testRunner.GivenAsync("User uses test data with ID \'BAR_006\' from \'BAref\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table55 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table55.AddRow(new string[] {
                            "town"});
                table55.AddRow(new string[] {
                            "postcode"});
                table55.AddRow(new string[] {
                            "uprn"});
                table55.AddRow(new string[] {
                            "effective_from_date"});
                table55.AddRow(new string[] {
                            "ba_reference"});
#line 427
 await testRunner.AndAsync("User connects to the DB and retrieves the \'1\' set of data for \'findHereditament_s" +
                        "wansea_BAREF\'", ((string)(null)), table55, "And ");
#line hidden
                global::Reqnroll.Table table56 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table56.AddRow(new string[] {
                            "town"});
                table56.AddRow(new string[] {
                            "postcode"});
                table56.AddRow(new string[] {
                            "uprn"});
                table56.AddRow(new string[] {
                            "effective_from_date"});
                table56.AddRow(new string[] {
                            "ba_reference"});
#line 435
 await testRunner.AndAsync("User connects to the DB and retrieves the \'2\' set of data for \'findHereditament_s" +
                        "wansea_BAREF\'", ((string)(null)), table56, "And ");
#line hidden
#line 442
 await testRunner.GivenAsync("User click on \'Requests\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 443
 await testRunner.AndAsync("User clicks on \'Discard changes\' button on \'Unsaved changes\' dialog,if appears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 444
 await testRunner.GivenAsync("User click on \'Requests\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 445
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 446
 await testRunner.AndAsync("User looked for \'Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 447
 await testRunner.AndAsync("User looked for \'Submitted By\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 448
 await testRunner.AndAsync("User entered 0 days before date for \'Date Received\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 449
 await testRunner.AndAsync("User enters \'2\' days after hereditament \'effective_from_date\' for \'Proposed Effec" +
                        "tive Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 450
 await testRunner.AndAsync("User looked for \'Data Source Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 451
 await testRunner.AndAsync("User clicks on \'Channel\' dropdown and select \'Email\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 452
 await testRunner.AndAsync("User enter data for \'BA Report Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 453
 await testRunner.AndAsync("User enter data for \'Reason For Validation\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 454
 await testRunner.AndAsync("User click on \'Find Hereditament\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 455
 await testRunner.AndAsync("User enters data in \"Postcode_new\" field for swap heriditament", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 456
 await testRunner.AndAsync("User clicked on \'Search\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 457
 await testRunner.AndAsync("User slects spcific \'uprn_new\' row from search hereditament results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 461
 await testRunner.AndAsync("User clicked on \'Select\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 462
 await testRunner.AndAsync("User waits till Find Hereditament dialog disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 463
 await testRunner.AndAsync("User clicks on \'Swap BA Reference Number?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 464
 await testRunner.AndAsync("User enter same hereditament BA ref number for \'Proposed BA Reference Number\' fie" +
                        "ld value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 465
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 467
 await testRunner.AndAsync("User verifies \'Proposed BA Reference Number : Invalid value of BA Reference Numbe" +
                        "r. To swap a BA Reference number the proposed BA Reference Number must match wit" +
                        "h existing hereditament\' Banner message", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 468
 await testRunner.AndAsync("User entered random number for \'Proposed BA Reference Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 469
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 470
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 471
 await testRunner.AndAsync("User verifies \'Proposed BA Reference Number : Invalid value of BA Reference Numbe" +
                        "r. To swap a BA Reference number the proposed BA Reference Number must match wit" +
                        "h existing hereditament\' Banner message", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 472
 await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
