// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace POMSeleniumFrameworkPoc1.Features.UI.E2E
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Consequentials")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("UI")]
    public partial class ConsequentialsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "UI"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/UI/E2E", "Consequentials", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Consequentials.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/UI/E2E/Consequentials.feature", 5);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("CBR01_CTPRELMGMT-1865_SIT - [CTPCASE-664] Consequential Band Review Correspondenc" +
            "e Band Decrease")]
        [global::NUnit.Framework.CategoryAttribute("Consequentials")]
        public async global::System.Threading.Tasks.Task CBR01_CTPRELMGMT_1865_SIT_CTPCASE_664ConsequentialBandReviewCorrespondenceBandDecrease()
        {
            string[] tagsOfScenario = new string[] {
                    "Consequentials"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CBR01_CTPRELMGMT-1865_SIT - [CTPCASE-664] Consequential Band Review Correspondenc" +
                    "e Band Decrease", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("User uses test data with ID \'CBR_001\' from \'ConsequentialsBandReview\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table78 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table78.AddRow(new string[] {
                            "uprn"});
                table78.AddRow(new string[] {
                            "effective_from_date"});
#line 8
 await testRunner.AndAsync("User connects to the DB and retrieves the data for \'findHereditament_WestLancashi" +
                        "re\'", ((string)(null)), table78, "And ");
#line hidden
#line 12
 await testRunner.AndAsync("User is logged in to Dynamics application to work for \"CBR_CTPRELMGMT-1865\" case", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
 await testRunner.AndAsync("User collapse if site map navigation expanded on left pane", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
 await testRunner.AndAsync("User click on \'Requests\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
 await testRunner.AndAsync("User looked for \'Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
 await testRunner.AndAsync("User looked for \'Submitted By\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
 await testRunner.AndAsync("User entered 0 days before date for \'Date Received\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.AndAsync("User entered 25 days before date for \'Proposed Effective Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
 await testRunner.AndAsync("User looked for \'Data Source Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
 await testRunner.AndAsync("User enter data for \'BA Report Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
 await testRunner.AndAsync("User enter data for \'Reason For Validation\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
 await testRunner.AndAsync("User click on \'Find Hereditament\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
 await testRunner.AndAsync("User select \'UPRN\' value from \'Search By\' dropdown", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
 await testRunner.AndAsync("User enters data in \"UPRN\" field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
 await testRunner.AndAsync("User clicked on \'Search\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
 await testRunner.AndAsync("User slects spcific \'uprn\' row from search hereditament results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
 await testRunner.AndAsync("User clicked on \'Select\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
 await testRunner.AndAsync("User waits till Find Hereditament dialog disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
 await testRunner.AndAsync("User clicks on \'Validate Request\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
 await testRunner.AndAsync("User waits till \'dialog\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
 await testRunner.AndAsync("User click on \'Related Jobs\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
 await testRunner.AndAsync("User captures \"Job ID\" and \"Job Name\" in \"featureContext\" by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
 await testRunner.AndAsync("User click on \'Jobs\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
 await testRunner.AndAsync("User \'Assign\' \'Job Name\' through \'All Jobs\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
 await testRunner.AndAsync("User click on \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
 await testRunner.AndAsync("User waits till \'Details\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Details\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
 await testRunner.AndAsync("User waits till \'Researching\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
 await testRunner.AndAsync("User clicked on \'PVT\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
 await testRunner.AndAsync("User selects \'Committed\' record", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
 await testRunner.AndAsync("User get PAD attributes of \'Committed\' record", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
 await testRunner.AndAsync("User clicked on \'Amend\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
 await testRunner.AndAsync("User clicks on \'Continue\' button on \'Clone and Amend PADs?\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
 await testRunner.AndAsync("user waits till app progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
 await testRunner.AndAsync("User clicked on \'PAD Entry\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
 await testRunner.AndAsync("User enter Property Attributes", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
 await testRunner.AndAsync("User looked for \'Conservatory Type\' field value only when data not entered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
 await testRunner.AndAsync("User enter data for \'Conservatory Area\' field value only when data not entered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
 await testRunner.AndAsync("User clicked on \'Add New Source Code\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
 await testRunner.AndAsync("User looked for \'Source Code\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
 await testRunner.AndAsync("User enter data for \'Comment\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
 await testRunner.AndAsync("user wait till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
 await testRunner.AndAsync("User scroll to \'PAD Validation\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
 await testRunner.AndAsync("User click on \'Validate PAD Code\' toggle button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
 await testRunner.AndAsync("user wait till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
 await testRunner.AndAsync("User validate value \'Pass\' for \'PAD Validation Outcome\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
 await testRunner.AndAsync("User clicked on \'Check Facts\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
 await testRunner.AndAsync("User clicks on \'Is Desktop Research Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Researching\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
 await testRunner.AndAsync("User waits till \'Undertake Banding\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
 await testRunner.AndAsync("User closes business process stage container", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Banding\' tab display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
 await testRunner.AndAsync("User clicked on \'Banding\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
 await testRunner.AndAsync("User enter data for Caseworker Conclusions / Remarks / Thought Process field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 88
 await testRunner.AndAsync("User looked for \'Proposed Tax Band\' and reduced 1 step from \"Current Tax Band\" ba" +
                        "nd value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
 await testRunner.AndAsync("User clicks on \'Is Banding Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
 await testRunner.AndAsync("User clicks on \'Confirm and Lock Banding\' button on \'Complete and Lock Banding\' d" +
                        "ialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Undertake Banding\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 93
 await testRunner.AndAsync("User waits till \'Maintain Assessment\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
 await testRunner.AndAsync("User closes business process stage container", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 95
 await testRunner.AndAsync("User clicked on \'Assessment\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 96
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
 await testRunner.AndAsync("User switchs to Assessment frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
 await testRunner.AndAsync("User clicked on \'Created Assessments\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table79 = new global::Reqnroll.Table(new string[] {
                            "Effective_From",
                            "Effective_To",
                            "TaxBand",
                            "CompIndicator",
                            "AssessmentStatus",
                            "PublicationStatus",
                            "AssessmentAction"});
                table79.AddRow(new string[] {
                            "Proposed Effective Date",
                            "",
                            "Proposed Tax Band",
                            "No",
                            "Current (live entry)",
                            "Unpublished",
                            "Alteration"});
#line 99
 await testRunner.AndAsync("User asserts below \'Created Assessments\' details", ((string)(null)), table79, "And ");
#line hidden
#line 102
 await testRunner.AndAsync("user asserts \'Created Assessments\' row count \'1\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 103
 await testRunner.AndAsync("user selects \'1\' Assessment and clicked on \'View\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
 await testRunner.AndAsync("User switchs to deafult frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 105
 await testRunner.AndAsync("user waits for \'2\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
 await testRunner.AndAsync("User asserts \'Change Code\' value as \'CL26 Band Review\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 107
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 108
 await testRunner.AndAsync("User clicks on \'Save and continue\' button on \'Unsaved changes\' dialog,if appears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 110
 await testRunner.AndAsync("User clicked on \'Maintain Assessment\' BPF Journey button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 111
 await testRunner.AndAsync("User clicks on \'Correspondence Checks Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 112
 await testRunner.AndAsync("User clicks on \'Maintain Assessment Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 113
 await testRunner.AndAsync("User clicks on \'Yes\' button on \'Complete Job\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 115
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Pending Release\' status dis" +
                        "play", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 117
 await testRunner.AndAsync("User clicked on \'Details\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 118
 await testRunner.AndAsync("User click on \'Request\' link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 119
 await testRunner.AndAsync("User clicks on \'Release and Publish\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 120
 await testRunner.AndAsync("User clicks on \'OK\' button element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 121
 await testRunner.AndAsync("User closes dialog if still present", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 122
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'List Updated\' status displa" +
                        "y", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
 await testRunner.AndAsync("User clicked on \'Assessment\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
 await testRunner.AndAsync("User switchs to Assessment frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
 await testRunner.AndAsync("User clicked on \'History\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table80 = new global::Reqnroll.Table(new string[] {
                            "Effective_From",
                            "Effective_To",
                            "TaxBand",
                            "CompIndicator",
                            "AssessmentStatus",
                            "PublicationStatus",
                            "AssessmentAction"});
                table80.AddRow(new string[] {
                            "Proposed Effective Date",
                            "",
                            "Proposed Tax Band",
                            "No",
                            "Current (live entry)",
                            "Published",
                            ""});
                table80.AddRow(new string[] {
                            "effective_from_date",
                            "Proposed Effective Date",
                            "Current Tax Band",
                            "No",
                            "Previously Current",
                            "Published",
                            ""});
#line 126
 await testRunner.AndAsync("User asserts below \'History\' details", ((string)(null)), table80, "And ");
#line hidden
#line 130
 await testRunner.AndAsync("User switchs to deafult frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 131
 await testRunner.AndAsync("User clicked on \'Outbound Correspondence\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 132
 await testRunner.AndAsync("User captures correspondence \"Job ID\" in \"featureContext\" by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 133
 await testRunner.AndAsync("User click on correspondence \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
 await testRunner.AndAsync("User clicks on \'Status Reason\' dropdown and select \'Ready\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 135
 await testRunner.AndAsync("User clicks on \'OK\' button on \'Outbound Correspondence\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 136
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 137
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 138
 await testRunner.AndAsync("User \'Refresh\' from \'menubar\' until \'Status Reason\' field set to \'Sent\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 139
 await testRunner.AndAsync("User selected \'Integration Messages\' under \'Related\' tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 140
 await testRunner.AndAsync("User click on messages \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 141
 await testRunner.AndAsync("User captures \'Message\' text area field in \'featureContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 142
 await testRunner.AndAsync("User validates \'Quadient Message\' contains \'CL26\' data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 143
 await testRunner.AndAsync("User clicks on \'Go back\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 144
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 145
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 146
 await testRunner.AndAsync("User clicked on \'Docuemnts\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 148
 await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Consequentials_DE01_CTPRELMGMT-504_SIT - CTPCASE-22 - Verify that Data Enhancemen" +
            "t Request and Job is created when New Property job is released and published & u" +
            "ser has identified Consequentials as Data enhancement")]
        [global::NUnit.Framework.CategoryAttribute("Consequentials")]
        public async global::System.Threading.Tasks.Task Consequentials_DE01_CTPRELMGMT_504_SIT_CTPCASE_22_VerifyThatDataEnhancementRequestAndJobIsCreatedWhenNewPropertyJobIsReleasedAndPublishedUserHasIdentifiedConsequentialsAsDataEnhancement()
        {
            string[] tagsOfScenario = new string[] {
                    "Consequentials"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consequentials_DE01_CTPRELMGMT-504_SIT - CTPCASE-22 - Verify that Data Enhancemen" +
                    "t Request and Job is created when New Property job is released and published & u" +
                    "ser has identified Consequentials as Data enhancement", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 151
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 152
 await testRunner.GivenAsync("User uses test data with ID \'NP_024\' from \'NewProperty\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 153
 await testRunner.AndAsync("User is logged in to Dynamics application to work for \"Consequentials_DE_CTPRELMG" +
                        "MT-504\" case", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 154
 await testRunner.AndAsync("User collapse if site map navigation expanded on left pane", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 155
 await testRunner.AndAsync("User click on \'Requests\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 156
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 157
 await testRunner.AndAsync("User looked for \'Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
 await testRunner.AndAsync("User looked for \'Submitted By\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 159
 await testRunner.AndAsync("User entered 0 days before date for \'Date Received\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 160
 await testRunner.AndAsync("User entered 25 days before date for \'Proposed Effective Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 161
 await testRunner.AndAsync("User scroll to \'Billing Authority Link\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 162
 await testRunner.AndAsync("User looked for \'Data Source Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 163
 await testRunner.AndAsync("User clicks on \'Channel\' dropdown and select \'Email\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 164
 await testRunner.AndAsync("User enter data for \'BA Report Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 165
 await testRunner.AndAsync("User enter data for \'Reason For Validation\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 166
 await testRunner.AndAsync("User scroll to \'New Hereditament Details\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 167
 await testRunner.AndAsync("User click on \'Find Address\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 168
 await testRunner.AndAsync("user enters data in \"Postcode\" and selects unique address in \'scenarioContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 169
 await testRunner.AndAsync("User scroll to \'Billing Authority Link\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 170
 await testRunner.AndAsync("User enter random number for \'Proposed BA Reference Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 171
 await testRunner.AndAsync("User scroll to \'Billing Authority Link\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 172
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 173
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 174
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 175
 await testRunner.AndAsync("User clicks on \'Validate Request\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 176
 await testRunner.AndAsync("User clicks on \'Proceed\' button on \'Confirm\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 177
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 178
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 179
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 180
 await testRunner.AndAsync("User click on \'Related Jobs\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 181
 await testRunner.AndAsync("User captures \"Job ID\" and \"Job Name\" in \"featureContext\" by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 184
 await testRunner.AndAsync("User click on \'Jobs\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 185
 await testRunner.AndAsync("User \'Assign\' \'Job Name\' through \'All Jobs\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 186
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 187
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 188
 await testRunner.AndAsync("User click on \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 189
 await testRunner.AndAsync("User waits till \'Details\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 190
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Details\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 191
 await testRunner.AndAsync("User waits till \'Researching\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 192
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 193
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 194
 await testRunner.AndAsync("User clicked on \'PVT\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 195
 await testRunner.AndAsync("User clicked on \'Create\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 196
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 197
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 198
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 199
 await testRunner.AndAsync("User looked for value \'19 - Houses and Bungalows built between 1908 and 1930\' in " +
                        "\'Group\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 200
 await testRunner.AndAsync("User looked for value \'BD - Detached bungalow\' in \'Type\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 201
 await testRunner.AndAsync("User looked for value \'B - 1900 - 1918\' in \'Age Code\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 202
 await testRunner.AndAsync("User enter data for \'Area\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 203
 await testRunner.AndAsync("User enter data for \'Rooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 204
 await testRunner.AndAsync("User enter data for \'Bedrooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 205
 await testRunner.AndAsync("User enter data for \'Bathrooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 206
 await testRunner.AndAsync("User enter data for \'Floors\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 207
 await testRunner.AndAsync("User enter data for \'Level\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 208
 await testRunner.AndAsync("User looked for value \'N - No Conservatory\' in \'Conservatory Type\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 209
 await testRunner.AndAsync("User looked for value \'G1 - Garaging\' in \'Parking\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 210
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 211
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 212
 await testRunner.AndAsync("User clicked on \'Add New Source Code\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 213
 await testRunner.AndAsync("User looked for \'Source Code\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 214
 await testRunner.AndAsync("User enter data for \'Comment\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 215
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 216
 await testRunner.AndAsync("user wait till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 218
 await testRunner.AndAsync("User scroll to \'PAD Validation\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 219
 await testRunner.AndAsync("User click on \'Validate PAD Code\' toggle button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 220
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 221
 await testRunner.AndAsync("user wait till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 222
 await testRunner.AndAsync("User validate value \'Pass\' for \'PAD Validation Outcome\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 223
 await testRunner.AndAsync("User clicked on \'Check Facts\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 224
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 225
 await testRunner.AndAsync("User clicks on \'Is Desktop Research Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 226
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 227
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 228
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Researching\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 229
 await testRunner.AndAsync("User waits till \'Undertake Banding\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 230
 await testRunner.AndAsync("User closes business process stage container", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 231
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Banding\' tab display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 232
 await testRunner.AndAsync("User clicked on \'Banding\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 233
 await testRunner.AndAsync("User enter data for Caseworker Conclusions / Remarks / Thought Process field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 234
 await testRunner.AndAsync("User looked for \'Proposed Tax Band\' single character field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 235
 await testRunner.AndAsync("User clicks on \'Is Banding Complete?\' dropdown and select \'No\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 236
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 237
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 238
 await testRunner.AndAsync("User clicked on \'Consequentials\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 239
 await testRunner.AndAsync("User clicks on \'Identify Consequentials\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 240
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table81 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table81.AddRow(new string[] {
                            "uprn"});
                table81.AddRow(new string[] {
                            "effective_from_date"});
#line 241
 await testRunner.AndAsync("User connects to the DB and retrieves the data for \'findHereditament_Manchester_N" +
                        "ew\'", ((string)(null)), table81, "And ");
#line hidden
#line 245
 await testRunner.AndAsync("User click on \'Find Hereditament\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 246
 await testRunner.AndAsync("User select \'UPRN\' value from \'Search By\' dropdown", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 247
 await testRunner.AndAsync("User enters data in \"UPRN\" field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 248
 await testRunner.AndAsync("User clicked on \'Search\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 249
 await testRunner.AndAsync("User slects spcific \'uprn\' row from search hereditament results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 250
 await testRunner.AndAsync("User clicked on \'Select\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 251
 await testRunner.AndAsync("User waits till Find Hereditament dialog disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 252
 await testRunner.AndAsync("User open consequential record", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 253
 await testRunner.AndAsync("User looked for \'Consequential Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 254
 await testRunner.AndAsync("User enter data for \'Remarks\' text area field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 255
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 256
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 257
 await testRunner.AndAsync("User clicked on \'Banding\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 258
 await testRunner.AndAsync("User clicks on \'Is Banding Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 259
 await testRunner.AndAsync("User clicks on \'Confirm and Lock Banding\' button on \'Complete and Lock Banding\' d" +
                        "ialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 260
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 261
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Undertake Banding\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 262
 await testRunner.AndAsync("User waits till \'Maintain Assessment\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 263
 await testRunner.AndAsync("User closes business process stage container", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 264
 await testRunner.AndAsync("User clicked on \'Assessment\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 265
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 266
 await testRunner.AndAsync("User switchs to Assessment frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 267
 await testRunner.AndAsync("User clicked on \'Created Assessments\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table82 = new global::Reqnroll.Table(new string[] {
                            "Effective_From",
                            "Effective_To",
                            "TaxBand",
                            "CompIndicator",
                            "AssessmentStatus",
                            "PublicationStatus",
                            "AssessmentAction"});
                table82.AddRow(new string[] {
                            "Proposed Effective Date",
                            "",
                            "Proposed Tax Band",
                            "No",
                            "Current (live entry)",
                            "Unpublished",
                            "New"});
#line 268
 await testRunner.AndAsync("User asserts below \'Created Assessments\' details", ((string)(null)), table82, "And ");
#line hidden
#line 271
 await testRunner.AndAsync("User switchs to deafult frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 272
 await testRunner.AndAsync("User clicked on \'Maintain Assessment\' BPF Journey button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 273
 await testRunner.AndAsync("User clicks on \'Correspondence Checks Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 274
 await testRunner.AndAsync("User clicks on \'Maintain Assessment Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 275
 await testRunner.AndAsync("User clicks on \'Yes\' button on \'Complete Job\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 276
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 277
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 278
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Pending Release\' status dis" +
                        "play", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 279
 await testRunner.AndAsync("User clicked on \'Details\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 280
 await testRunner.AndAsync("User click on \'Request\' link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 281
 await testRunner.AndAsync("User clicks on \'Release and Publish\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 282
 await testRunner.AndAsync("User clicks on \'OK\' button element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 283
 await testRunner.AndAsync("User closes dialog if still present", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 284
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'List Updated\' status displa" +
                        "y", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 285
 await testRunner.AndAsync("User clicked on \'Assessment\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 286
 await testRunner.AndAsync("User switchs to Assessment frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 287
 await testRunner.AndAsync("User clicked on \'History\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table83 = new global::Reqnroll.Table(new string[] {
                            "Effective_From",
                            "Effective_To",
                            "TaxBand",
                            "CompIndicator",
                            "AssessmentStatus",
                            "PublicationStatus",
                            "AssessmentAction"});
                table83.AddRow(new string[] {
                            "Proposed Effective Date",
                            "",
                            "Proposed Tax Band",
                            "No",
                            "Current (live entry)",
                            "Published",
                            "New"});
#line 288
 await testRunner.AndAsync("User asserts below \'History\' details", ((string)(null)), table83, "And ");
#line hidden
#line 291
 await testRunner.AndAsync("User switchs to deafult frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 292
 await testRunner.AndAsync("User clicked on \'PVT\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table84 = new global::Reqnroll.Table(new string[] {
                            "AssessmentStatus",
                            "TaxBand",
                            "Effective_From",
                            "Effective_To",
                            "DOLU_Identifier",
                            "ListUpdateAction",
                            "CompIndicator",
                            "Job"});
                table84.AddRow(new string[] {
                            "Current (live entry)",
                            "Proposed Tax Band",
                            "Proposed Effective Date",
                            "",
                            "No",
                            "Insertion",
                            "No",
                            "Job Name"});
#line 293
 await testRunner.AndAsync("User validate \'Assessments\' details under \'PVT\' tab", ((string)(null)), table84, "And ");
#line hidden
#line 296
 await testRunner.AndAsync("User clicked on \'Consequentials\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 297
 await testRunner.AndAsync("User open consequential record", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 298
 await testRunner.AndAsync("user waits for \'180\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 299
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Succeeding Request\' has val" +
                        "ue display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 300
 await testRunner.AndAsync("User navigate to \'Succeeding Request\' from consequential review item", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table85 = new global::Reqnroll.Table(new string[] {
                            "fieldName",
                            "value",
                            "feieldType"});
                table85.AddRow(new string[] {
                            "Date Received",
                            "Today",
                            "input"});
                table85.AddRow(new string[] {
                            "Target Date",
                            "Today+5",
                            "input"});
                table85.AddRow(new string[] {
                            "Data Source Role",
                            "Listing Officer Report",
                            "LookUp"});
                table85.AddRow(new string[] {
                            "Job Type",
                            "Data Enhancement",
                            "Lookup"});
                table85.AddRow(new string[] {
                            "Originating Job",
                            "Job Name",
                            "Lookup"});
#line 301
 await testRunner.AndAsync("user asserts below fields for consequentials review item \'Data Enhancement \'", ((string)(null)), table85, "And ");
#line hidden
#line 312
 await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Consequentials02_[SIT] [CTPCASE-167]- Validate the Send CT Notice of Alteration V" +
            "O 7704 is generated if Band Decrease for Consequential Band Change-England Hered" +
            "itament")]
        [global::NUnit.Framework.CategoryAttribute("Consequentials")]
        public async global::System.Threading.Tasks.Task Consequentials02_SITCTPCASE_167_ValidateTheSendCTNoticeOfAlterationVO7704IsGeneratedIfBandDecreaseForConsequentialBandChange_EnglandHereditament()
        {
            string[] tagsOfScenario = new string[] {
                    "Consequentials"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consequentials02_[SIT] [CTPCASE-167]- Validate the Send CT Notice of Alteration V" +
                    "O 7704 is generated if Band Decrease for Consequential Band Change-England Hered" +
                    "itament", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 316
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 317
 await testRunner.GivenAsync("User uses test data with ID \'MR_003\' from \'MaterialRedcution\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table86 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table86.AddRow(new string[] {
                            "uprn"});
                table86.AddRow(new string[] {
                            "effective_from_date"});
#line 318
 await testRunner.AndAsync("User connects to the DB and retrieves the data for \'findHereditament_WestLancashi" +
                        "re\'", ((string)(null)), table86, "And ");
#line hidden
#line 322
 await testRunner.AndAsync("User is logged in to Dynamics application to work for \"MR_E2E_80581\" case", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 323
 await testRunner.AndAsync("User collapse if site map navigation expanded on left pane", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 324
 await testRunner.AndAsync("User click on \'Requests\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 325
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 326
 await testRunner.AndAsync("User looked for \'Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 327
 await testRunner.AndAsync("User looked for \'Submitted By\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 329
 await testRunner.AndAsync("User entered 0 days before date for \'Date Received\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 330
 await testRunner.AndAsync("User entered 25 days before date for \'Proposed Effective Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 331
 await testRunner.AndAsync("User scroll to \'Planning Details\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 332
 await testRunner.AndAsync("User enter data for \'Reason for Portal Reference Omission\' text area field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 333
 await testRunner.AndAsync("User looked for \'Data Source Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 334
 await testRunner.AndAsync("User clicks on \'Channel\' dropdown and select \'Email\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 335
 await testRunner.AndAsync("User enter data for \'BA Report Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 336
 await testRunner.AndAsync("User enter data for \'Reason For Validation\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 337
 await testRunner.AndAsync("User click on \'Find Hereditament\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 338
 await testRunner.AndAsync("User select \'UPRN\' value from \'Search By\' dropdown", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 339
 await testRunner.AndAsync("User enters data in \"UPRN\" field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 340
 await testRunner.AndAsync("User clicked on \'Search\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 341
 await testRunner.AndAsync("User slects spcific \'uprn\' row from search hereditament results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 342
 await testRunner.AndAsync("User clicked on \'Select\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 343
 await testRunner.AndAsync("User waits till Find Hereditament dialog disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 344
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 345
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 346
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 347
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 348
 await testRunner.AndAsync("User clicks on \'Validate Request\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 349
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 350
 await testRunner.AndAsync("User waits till \'dialog\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 351
 await testRunner.AndAsync("User click on \'Related Jobs\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 352
 await testRunner.AndAsync("User captures \"Job ID\" and \"Job Name\" in \"featureContext\" by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 355
 await testRunner.AndAsync("User click on \'Jobs\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 356
 await testRunner.AndAsync("User \'Assign\' \'Job Name\' through \'All Jobs\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 357
 await testRunner.AndAsync("user waits till progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 358
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 359
 await testRunner.AndAsync("User click on \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 360
 await testRunner.AndAsync("User waits till \'Details\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 361
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Details\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 362
 await testRunner.AndAsync("User waits till \'Researching\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 363
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 364
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table87 = new global::Reqnroll.Table(new string[] {
                            "Questions"});
                table87.AddRow(new string[] {
                            "Is it part of an on-going scheme?"});
                table87.AddRow(new string[] {
                            "Are plans available?"});
                table87.AddRow(new string[] {
                            "Are the adaptations for a disabled person?"});
                table87.AddRow(new string[] {
                            "Has there been a change to the physical state of the locality?"});
#line 365
 await testRunner.AndAsync("User validates questionnaire in the \'Researching\' stage", ((string)(null)), table87, "And ");
#line hidden
#line 371
 await testRunner.AndAsync("User clicked on \'PVT\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 372
 await testRunner.AndAsync("User selects \'Committed\' record", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 373
 await testRunner.AndAsync("User get PAD attributes of \'Committed\' record", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 374
 await testRunner.AndAsync("User clicked on \'Clone to New Date\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 375
 await testRunner.AndAsync("User clicked on \'Committed\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 376
 await testRunner.AndAsync("User entered 25 days before date from calender for \'Enter the Effective Date for " +
                        "the new set of PADs\' field value on \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 377
 await testRunner.AndAsync("User clicked on \'Continue\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 378
 await testRunner.AndAsync("user waits till app progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 380
 await testRunner.AndAsync("User clicked on \'PAD Entry\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 381
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 382
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 384
 await testRunner.AndAsync("User enter Property Attributes", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 388
 await testRunner.AndAsync("User looked for \'Conservatory Type\' field value only when data not entered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 389
 await testRunner.AndAsync("User enter data for \'Conservatory Area\' field value only when data not entered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 390
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 391
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 392
 await testRunner.AndAsync("User clicked on \'Add New Source Code\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 393
 await testRunner.AndAsync("User looked for \'Source Code\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 394
 await testRunner.AndAsync("User enter data for \'Comment\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 395
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 396
 await testRunner.AndAsync("user wait till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 397
 await testRunner.AndAsync("User scroll to \'PAD Validation\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 398
 await testRunner.AndAsync("User click on \'Validate PAD Code\' toggle button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 399
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 400
 await testRunner.AndAsync("user wait till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 401
 await testRunner.AndAsync("User validate value \'Pass\' for \'PAD Validation Outcome\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 402
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 403
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 404
 await testRunner.AndAsync("User clicked on \'Check Facts\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 405
 await testRunner.AndAsync("User clicks on \'Is Desktop Research Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 406
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 407
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 408
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Researching\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 409
 await testRunner.AndAsync("User waits till \'Undertake Banding\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 411
 await testRunner.AndAsync("User closes business process stage container", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 412
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Banding\' tab display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 413
 await testRunner.AndAsync("User clicked on \'Banding\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 414
 await testRunner.AndAsync("User enter data for Caseworker Conclusions / Remarks / Thought Process field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 415
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 416
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
