// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace POMSeleniumFrameworkPoc1.Features.UI.E2E
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("CRM Enquiries Regression")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("UI")]
    public partial class CRMEnquiriesRegressionFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "UI"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/UI/E2E", "CRM Enquiries Regression", "\t Validate Informal Challenge Features", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "CRMEnquiries.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/UI/E2E/CRMEnquiries.feature", 5);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("CRMEnquiries01_CTPRELMGMT-1714_CTPRELMGMT-1713_CTPRELMGMT-1712_CTPRELMGMT-1497 Re" +
            "solving & Reactivating the Enquiry")]
        [global::NUnit.Framework.CategoryAttribute("CRMEnquiries")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        [global::NUnit.Framework.CategoryAttribute("P1_A")]
        public async global::System.Threading.Tasks.Task CRMEnquiries01_CTPRELMGMT_1714_CTPRELMGMT_1713_CTPRELMGMT_1712_CTPRELMGMT_1497ResolvingReactivatingTheEnquiry()
        {
            string[] tagsOfScenario = new string[] {
                    "CRMEnquiries",
                    "Regression",
                    "P1_A"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CRMEnquiries01_CTPRELMGMT-1714_CTPRELMGMT-1713_CTPRELMGMT-1712_CTPRELMGMT-1497 Re" +
                    "solving & Reactivating the Enquiry", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
 await testRunner.GivenAsync("User uses test data with ID \'Proposals_005\' from \'Proposals\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table88 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table88.AddRow(new string[] {
                            "uprn"});
                table88.AddRow(new string[] {
                            "effective_from_date"});
#line 10
 await testRunner.AndAsync("User connects to the DB and retrieves the data for \'findhereditamentForDel\'", ((string)(null)), table88, "And ");
#line hidden
#line 14
 await testRunner.AndAsync("User is logged in", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
 await testRunner.GivenAsync("User click on \'Customer Enquiries\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.AndAsync("User looked for value \'Test Customer\' in \'Customer\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
 await testRunner.AndAsync("User looked for \'Customer Relationship Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
 await testRunner.AndAsync("User entered 0 days before date for \'Date Received in VOA\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
 await testRunner.AndAsync("User entered 25 days after date for \'Evidence Sufficient Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
 await testRunner.AndAsync("User clicks on \'Channel\' dropdown and select \'Phone\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
 await testRunner.AndAsync("User looked for \'Task Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
 await testRunner.AndAsync("User looked for \'Contact Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
 await testRunner.AndAsync("User looked for \'Cust. Enquiry Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
 await testRunner.AndAsync("User looked for \'To Unit\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
 await testRunner.AndAsync("User looked for \'Cust. Enquiry Sub Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
 await testRunner.AndAsync("User looked for \'Cust. Enquiry Sub Type 2\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
 await testRunner.AndAsync("User looked for value \'Test CouncilTaxPayer\' in \'Council Tax Payer\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
 await testRunner.AndAsync("User clicks on \'Authority to Act Received\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
 await testRunner.AndAsync("User validates the status as \'Pending Validation\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
 await testRunner.AndAsync("User clicks on \'Resolve\' on the commandbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
 await testRunner.AndAsync("User selects \'Answered\' as Status Reason and \'Deactivate\' the Enquiry", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
 await testRunner.AndAsync("User validates the status as \'Answered\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
 await testRunner.AndAsync("User clicks on \'Activate\' on the commandbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
 await testRunner.AndAsync("User selects \'Pending Validation\' as Status Reason and \'Activate\' the Enquiry", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
 await testRunner.AndAsync("User validates the status as \'Pending Validation\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
 await testRunner.AndAsync("User clicks on \'Resolve\' on the commandbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
 await testRunner.AndAsync("User selects \'No Action\' as Status Reason and \'Deactivate\' the Enquiry", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
 await testRunner.AndAsync("User validates the status as \'No Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
 await testRunner.AndAsync("User clicks on \'Activate\' on the commandbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
 await testRunner.AndAsync("User selects \'Refer to Complaints Team\' as Status Reason and \'Activate\' the Enqui" +
                        "ry", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
 await testRunner.AndAsync("User validates the status as \'Refer to Complaints Team\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("CRMEnquiries02_CTPRELMGMT-1458")]
        [global::NUnit.Framework.CategoryAttribute("CRMEnquiries")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        [global::NUnit.Framework.CategoryAttribute("P1_A")]
        public async global::System.Threading.Tasks.Task CRMEnquiries02_CTPRELMGMT_1458()
        {
            string[] tagsOfScenario = new string[] {
                    "CRMEnquiries",
                    "Regression",
                    "P1_A"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CRMEnquiries02_CTPRELMGMT-1458", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 50
 await testRunner.GivenAsync("User uses test data with ID \'Proposals_005\' from \'Proposals\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 52
 await testRunner.AndAsync("User is logged in to Dynamics application to work for \"1481_E2E_Proposals_MR\" cas" +
                        "e", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
 await testRunner.AndAsync("User collapse if site map navigation expanded on left pane", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table89 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table89.AddRow(new string[] {
                            "uprn"});
                table89.AddRow(new string[] {
                            "effective_from_date"});
#line 54
 await testRunner.AndAsync("User connects to the DB and retrieves the data for \'findHereditament_CAMBRIDGE\'", ((string)(null)), table89, "And ");
#line hidden
#line 58
 await testRunner.AndAsync("User click on \'Customer Enquiries\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
 await testRunner.AndAsync("User looked for value \'Test Customer\' in \'Customer\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
 await testRunner.AndAsync("User looked for \'Customer Relationship Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
 await testRunner.AndAsync("User entered 0 days before date for \'Date Received in VOA\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
 await testRunner.AndAsync("User entered 25 days after date for \'Evidence Sufficient Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
 await testRunner.AndAsync("User clicks on \'Channel\' dropdown and select \'Phone\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
 await testRunner.AndAsync("User looked for \'Task Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
 await testRunner.AndAsync("User looked for \'Contact Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
 await testRunner.AndAsync("User looked for \'Cust. Enquiry Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
 await testRunner.AndAsync("User looked for \'To Unit\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
 await testRunner.AndAsync("User looked for \'Cust. Enquiry Sub Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
 await testRunner.AndAsync("User looked for \'Cust. Enquiry Sub Type 2\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
 await testRunner.AndAsync("User looked for value \'Test CouncilTaxPayer\' in \'Council Tax Payer\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
 await testRunner.AndAsync("User clicks on \'Authority to Act Received\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
 await testRunner.AndAsync("User clicks on \'Supplementary Job Requisition\' under \'Raise Enquiry Actions\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
 await testRunner.AndAsync("User looked for \'Request Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
 await testRunner.AndAsync("User looked for \'Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
 await testRunner.AndAsync("User looked for \'Reason/Ground\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
 await testRunner.AndAsync("User enters random days after hereditament \'effective_from_date\' for \'Proposed Ef" +
                        "fective Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
 await testRunner.AndAsync("User clicked on 2 position \'Find Hereditament\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
 await testRunner.AndAsync("User select \'UPRN\' value from \'Search By\' dropdown", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
 await testRunner.AndAsync("User enters data in \"UPRN\" field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
 await testRunner.AndAsync("User clicked on \'Search\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
 await testRunner.AndAsync("User slects spcific \'uprn\' row from search hereditament results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 88
 await testRunner.AndAsync("User clicked on \'Select\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
 await testRunner.AndAsync("User waits till Find Hereditament dialog disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
 await testRunner.AndAsync("User click on \'Save\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
 await testRunner.AndAsync("User click on \'Submit\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 93
 await testRunner.AndAsync("User clicks on \'Continue\' button on \'Confirm Supplementary Job Requisition\' dialo" +
                        "g", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 95
 await testRunner.AndAsync("User closes dialog if still present", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 96
 await testRunner.AndAsync("User click on \'Supplementary Requests\' tab from \'Customer Enquiry Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
 await testRunner.AndAsync("User clicked on supplementary job id", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
 await testRunner.AndAsync("user waits for \'5\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
 await testRunner.AndAsync("User scroll to \'Remarks\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 100
 await testRunner.AndAsync("User scroll to \'Authority to Act\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 101
 await testRunner.AndAsync("User clicks on \'Authority to Act Received\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 102
 await testRunner.AndAsync("User looked for \'Reason/Ground\' field value only when data not entered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 103
 await testRunner.AndAsync("User looked for \'Data Source Role\' field value only when data not entered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("CRMEnquiries03_CTPRELMGMT-1448_CTPRELMGMT-1537_[SIT] - Welsh Reform Proposal - Va" +
            "lidate creation of SLA item for Tier 2 Referral")]
        [global::NUnit.Framework.CategoryAttribute("CRMEnquiries")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        public async global::System.Threading.Tasks.Task CRMEnquiries03_CTPRELMGMT_1448_CTPRELMGMT_1537_SIT_WelshReformProposal_ValidateCreationOfSLAItemForTier2Referral()
        {
            string[] tagsOfScenario = new string[] {
                    "CRMEnquiries",
                    "Regression"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CRMEnquiries03_CTPRELMGMT-1448_CTPRELMGMT-1537_[SIT] - Welsh Reform Proposal - Va" +
                    "lidate creation of SLA item for Tier 2 Referral", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 107
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 108
await testRunner.GivenAsync("User uses test data with ID \'Proposals_005\' from \'Proposals\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 109
await testRunner.AndAsync("User is logged in to Dynamics application to work for \"Tier2_SLA\" case", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 110
await testRunner.AndAsync("User collapse if site map navigation expanded on left pane", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 111
await testRunner.GivenAsync("User click on \'Customer Enquiries\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 112
await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 113
await testRunner.AndAsync("User looked for value \'Test Customer\' in \'Customer\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
await testRunner.AndAsync("User looked for \'Customer Relationship Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 115
await testRunner.AndAsync("User entered 0 days before date for \'Date Received in VOA\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
await testRunner.AndAsync("User entered 25 days after date for \'Evidence Sufficient Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 117
await testRunner.AndAsync("User clicks on \'Channel\' dropdown and select \'Phone\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 118
await testRunner.AndAsync("User looked for \'Task Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 119
await testRunner.AndAsync("User looked for \'Contact Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 120
await testRunner.AndAsync("User looked for \'Cust. Enquiry Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 121
await testRunner.AndAsync("User looked for \'To Unit\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 122
await testRunner.AndAsync("User looked for \'Cust. Enquiry Sub Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
await testRunner.AndAsync("User looked for \'Cust. Enquiry Sub Type 2\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
await testRunner.AndAsync("User looked for value \'Test CouncilTaxPayer\' in \'Council Tax Payer\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
await testRunner.AndAsync("User clicks on \'Authority to Act Received\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 126
await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 128
await testRunner.AndAsync("User validates the status as \'Pending Validation\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 129
await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 130
await testRunner.AndAsync("User scroll to \'Customer Enquiry SLA\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 131
await testRunner.AndAsync("user validated \'Customer Enquiry SLA KPI\' contains text", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 132
await testRunner.AndAsync("User click on \'Is Expression of Dissatisfaction\' toggle button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 133
await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 135
await testRunner.AndAsync("verify status reason as \'Refer to Complaints Team\' in the property link page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 136
await testRunner.AndAsync("User click on \'Tier 2 Referral ?\' toggle button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 137
await testRunner.AndAsync("User enter data for \'Reason for Tier2 Referral\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 138
await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 139
await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 140
await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 141
await testRunner.AndAsync("User scroll to \'Customer Enquiry SLA\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 142
await testRunner.AndAsync("user validated \'Tier 2 escalation SLA KPI\' contains text", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 143
await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
