// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace POMSeleniumFrameworkPoc1.Features.UI.E2E
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Milo")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("UI")]
    public partial class MiloFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "UI"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/UI/E2E", "Milo", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Milo.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/UI/E2E/Milo.feature", 4);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("MILO01_CTPRELMGMT-1417_CTPRELMGMT-1430-[SIT]-[BST-149659]-Verify a hereditament c" +
            "an be linked to and unlinked from a MILO Transaction in Dynamics")]
        [global::NUnit.Framework.CategoryAttribute("Milo")]
        [global::NUnit.Framework.CategoryAttribute("E2E")]
        [global::NUnit.Framework.CategoryAttribute("P1_C")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        [global::NUnit.Framework.CategoryAttribute("mini_Regression")]
        public async global::System.Threading.Tasks.Task MILO01_CTPRELMGMT_1417_CTPRELMGMT_1430_SIT_BST_149659_VerifyAHereditamentCanBeLinkedToAndUnlinkedFromAMILOTransactionInDynamics()
        {
            string[] tagsOfScenario = new string[] {
                    "Milo",
                    "E2E",
                    "P1_C",
                    "Regression",
                    "mini_Regression"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("MILO01_CTPRELMGMT-1417_CTPRELMGMT-1430-[SIT]-[BST-149659]-Verify a hereditament c" +
                    "an be linked to and unlinked from a MILO Transaction in Dynamics", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await testRunner.GivenAsync("User uses test data with ID \'Milo_001\' from \'TestDataPart3\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table294 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table294.AddRow(new string[] {
                            "town"});
                table294.AddRow(new string[] {
                            "postcode"});
                table294.AddRow(new string[] {
                            "uprn"});
                table294.AddRow(new string[] {
                            "effective_from_date"});
#line 9
await testRunner.AndAsync("User connects to the DB and retrieves the data for \'FindHereditamentforEnglishHer" +
                        "editament_birmingham\'", ((string)(null)), table294, "And ");
#line hidden
#line 15
 await testRunner.GivenAsync("User is logged in to Dynamics application to work for \"Milo_process_Linking\" case" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 16
 await testRunner.AndAsync("User collapse if site map navigation expanded on left pane", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
 await testRunner.GivenAsync("User click on \'MILO Transactions\' under \'Search Tools\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
 await testRunner.AndAsync("User clicks \'Active MILO Transactions\' dropdown and filters \'UnLinked MILO Transa" +
                        "ctions\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.AndAsync("User captures the \'Name\' in \'scenariocontext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
 await testRunner.AndAsync("User click on \'Link Hereditament\' on the menubar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
 await testRunner.AndAsync("User select \'UPRN\' value from \'Search By\' dropdown for milo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
 await testRunner.AndAsync("User enters data in \"UPRN\" field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
 await testRunner.AndAsync("User clicked on 2 position \'Search\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
 await testRunner.AndAsync("User select specific \'uprn\' row from search hereditament results and save in \'sce" +
                        "narioContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
 await testRunner.AndAsync("User clicked on \'Select\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
 await testRunner.AndAsync("user waits for \'5\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
 await testRunner.AndAsync("User clicks on \'Close\' button on \'Success\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
 await testRunner.AndAsync("User filters the \'Name\' through \'Linked MILO Transactions\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
 await testRunner.AndAsync("User click on Hereditament link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
 await testRunner.AndAsync("User clicked on \'PVT\' tab under \'Hereditament Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
 await testRunner.AndAsync("User click on \'MILO Transactions\' tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
 await testRunner.AndAsync("User validate milorecord and click on \'UnLink\' transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
 await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("MILO02_CTPRELMGMT-1431-[SIT]-[SIT] [BST-149749] - Validate user can soft delete &" +
            " un-delete the Milo record")]
        [global::NUnit.Framework.CategoryAttribute("Milo")]
        [global::NUnit.Framework.CategoryAttribute("E2E")]
        [global::NUnit.Framework.CategoryAttribute("P1_C")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        [global::NUnit.Framework.CategoryAttribute("mini_Regression")]
        public async global::System.Threading.Tasks.Task MILO02_CTPRELMGMT_1431_SIT_SITBST_149749_ValidateUserCanSoftDeleteUn_DeleteTheMiloRecord()
        {
            string[] tagsOfScenario = new string[] {
                    "Milo",
                    "E2E",
                    "P1_C",
                    "Regression",
                    "mini_Regression"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("MILO02_CTPRELMGMT-1431-[SIT]-[SIT] [BST-149749] - Validate user can soft delete &" +
                    " un-delete the Milo record", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 49
await testRunner.GivenAsync("User is logged in to Dynamics application to work for \"Milo_process_soft delete &" +
                        " un-delete\" case", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 50
await testRunner.AndAsync("User collapse if site map navigation expanded on left pane", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
await testRunner.GivenAsync("User click on \'MILO Transactions\' under \'Search Tools\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 52
await testRunner.AndAsync("User clicks \'Active MILO Transactions\' dropdown and filters \'Inactive MILO Transa" +
                        "ctions\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
await testRunner.AndAsync("User captures the \'Name\' in \'scenariocontext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
await testRunner.AndAsync("User click on \'Activate\' on the menubar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
await testRunner.AndAsync("User clicks on \'Activate\' button on \'Confirm MILO Transaction Activation\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
await testRunner.AndAsync("user waits for \'5\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
await testRunner.AndAsync("User clicks on the  \'Inactive MILO Transactions\' dropdown and filters \'Active MIL" +
                        "O Transactions\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
await testRunner.AndAsync("User filters the \'Name\' through \'Active MILO Transactions\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
await testRunner.GivenAsync("User click on \'MILO Transactions\' under \'Search Tools\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 60
await testRunner.AndAsync("User clicks \'Active MILO Transactions\' dropdown and filters \'Linked MILO Transact" +
                        "ions\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
await testRunner.AndAsync("User captures the \'Name\' in \'scenariocontext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
await testRunner.AndAsync("User click on \'Deactivate\' on the menubar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
await testRunner.AndAsync("User clicks on \'Deactivate\' button on \'Confirm Deactivation\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
await testRunner.AndAsync("User clicks on the  \'Linked MILO Transactions\' dropdown and filters \'Inactive MIL" +
                        "O Transactions\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
await testRunner.AndAsync("User filters the \'Name\' through \'Active MILO Transactions\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
