// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace POMSeleniumFrameworkPoc1.Features.UI.E2E
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("NewProperty test data genarator")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("UI")]
    public partial class NewPropertyTestDataGenaratorFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "UI"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/UI/E2E", "NewProperty test data genarator", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "NewProperty_TestGenerator.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/UI/E2E/NewProperty_TestGenerator.feature", 19);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("NP_TD01_NewProperty Creation")]
        [global::NUnit.Framework.CategoryAttribute("TestDataGenerator")]
        [global::NUnit.Framework.TestCaseAttribute("1", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("2", "1", null)]
        public async global::System.Threading.Tasks.Task NP_TD01_NewPropertyCreation(string iterations, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TestDataGenerator"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Iterations", iterations);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("NP_TD01_NewProperty Creation", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync(string.Format("I run the scenario {0} times", iterations), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.GivenAsync("User uses test data with ID \'NP_003\' from \'TestDataPart3\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
 await testRunner.GivenAsync("User is logged in to Dynamics application to work for \"NewProp_TD_Generator\" case" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 11
 await testRunner.GivenAsync("User click on \'Submissions\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
 await testRunner.AndAsync("User looked for \'Integration Data Source\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
 await testRunner.AndAsync("User looked for \'Submitted By\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
 await testRunner.AndAsync("User looked for \'Relationship Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
 await testRunner.AndAsync("User scroll to \'Related Requests\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
 await testRunner.AndAsync("User click \'New Request\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.AndAsync("User looked for \'Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
 await testRunner.AndAsync("User entered 0 days before date for \'Date Received\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
 await testRunner.AndAsync("User entered 25 days before date for \'Proposed Effective Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
 await testRunner.AndAsync("User looked for \'Data Source Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
 await testRunner.AndAsync("User enter data for \'BA Report Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
 await testRunner.AndAsync("User enter data for \'Reason For Validation\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
 await testRunner.AndAsync("User scroll to \'Billing Authority Link\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
 await testRunner.AndAsync("User enter random number for \'Proposed BA Reference Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
 await testRunner.AndAsync("User scroll to \'New Hereditament Details\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
 await testRunner.AndAsync("User click on \'Find Address\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
 await testRunner.AndAsync("user enters data in \"Postcode\" and selects unique address in \'scenarioContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
 await testRunner.AndAsync("User clicks on \'Validate Request\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
 await testRunner.AndAsync("User clicks on \'Proceed\' button on \'Confirm\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
 await testRunner.AndAsync("User click on \'Related Jobs\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
 await testRunner.AndAsync("User captures \"Job ID\" and \"Job Name\" in \"scenarioContext\" by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
 await testRunner.AndAsync("User click on \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
 await testRunner.AndAsync("User waits till \'Details\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
 await testRunner.AndAsync("User \'Assign\' job to self on \'Assign to Team or User\' pop-up", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
 await testRunner.AndAsync("user waits till app progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Details\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
 await testRunner.AndAsync("User waits till \'Researching\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
 await testRunner.AndAsync("User clicked on \'PVT\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
 await testRunner.AndAsync("User clicked on \'Create\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
 await testRunner.AndAsync("User clicks on \'Save and continue\' button on \'Unsaved changes\' dialog,if appears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
 await testRunner.AndAsync("User looked for first element \'Group\' field value only when data not entered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
 await testRunner.AndAsync("User looked for first element \'Type\' field value only when data not entered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
 await testRunner.AndAsync("User looked for first element \'Age Code\' field value only when data not entered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
 await testRunner.AndAsync("User enter data for \'Area\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
 await testRunner.AndAsync("User enter data for \'Rooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
 await testRunner.AndAsync("User enter data for \'Bedrooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
 await testRunner.AndAsync("User enter data for \'Bathrooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
 await testRunner.AndAsync("User enter data for \'Floors\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
 await testRunner.AndAsync("User enter data for \'Level\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
 await testRunner.AndAsync("User looked for \'Parking\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
 await testRunner.AndAsync("User looked for \'Conservatory Type\' field value only when data not entered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
 await testRunner.AndAsync("User clicked on \'Add New Source Code\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
 await testRunner.AndAsync("User looked for \'Source Code\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
 await testRunner.AndAsync("User enter data for \'Comment\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
 await testRunner.AndAsync("user waits till app progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
 await testRunner.AndAsync("User scroll to \'PAD Validation\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
 await testRunner.AndAsync("User click on \'Validate PAD Code\' toggle button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
 await testRunner.AndAsync("user wait till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 88
 await testRunner.AndAsync("User validate value \'Pass\' for \'PAD Validation Outcome\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Researching\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
 await testRunner.AndAsync("User waits till \'Undertake Banding\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 93
 await testRunner.AndAsync("User clicked on \'Undertake Banding\' BPF Journey button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 95
 await testRunner.AndAsync("User closes business process stage container", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 96
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Banding\' tab display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
 await testRunner.AndAsync("User clicked on \'Banding\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
 await testRunner.AndAsync("User enter data for Caseworker Conclusions / Remarks / Thought Process field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 100
 await testRunner.AndAsync("User looked for \'Proposed Tax Band\' single character field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 102
 await testRunner.AndAsync("User clicks on \'Is Banding Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 103
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 105
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Undertake Banding\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
 await testRunner.AndAsync("User waits till \'Maintain Assessment\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 107
 await testRunner.AndAsync("User closes business process stage container", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 108
 await testRunner.AndAsync("User clicked on \'Assessment\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 110
 await testRunner.AndAsync("user waits for \'1\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 111
 await testRunner.AndAsync("User switchs to Assessment frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 112
 await testRunner.AndAsync("user waits for \'1\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 113
 await testRunner.AndAsync("User clicked on \'Proposed Assessments\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
 await testRunner.AndAsync("user asserts \'Proposed Assessments\' row count \'1\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 115
 await testRunner.AndAsync("User switchs to deafult frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
 await testRunner.AndAsync("User clicked on \'Maintain Assessment\' BPF Journey button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 117
 await testRunner.AndAsync("User clicks on \'Correspondence Checks Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 118
 await testRunner.AndAsync("User clicks on \'Maintain Assessment Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 121
 await testRunner.AndAsync("User clicks on \'Yes\' button on \'All Jobs Created for Request\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 122
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'List Updated\' status displa" +
                        "y", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
 await testRunner.AndAsync("User clicked on \'Details\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
 await testRunner.AndAsync("User scroll to \'Hereditament Details\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
 await testRunner.AndAsync("User captures \'Address String\' input field in \'scenarioContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 126
 await testRunner.AndAsync("User captures \'Job ID\' input field in \'scenarioContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
 await testRunner.AndAsync("User captures the \'Job ID\',\'Address String\' data in the \'NewPropOutPutData\' outpu" +
                        "t sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 128
 await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("NP_TD02_Band_NewProperty Creation with Modified Band Values")]
        [global::NUnit.Framework.CategoryAttribute("TestDataGenerator")]
        [global::NUnit.Framework.TestCaseAttribute("1", "A", "B13 0TB", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("2", "B", "B13 0TB", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("3", "A", "CF11 7AR", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("4", "B", "CF11 7AR", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("5", "B", "CF11 7AR", "6", null)]
        public async global::System.Threading.Tasks.Task NP_TD02_Band_NewPropertyCreationWithModifiedBandValues(string iterations, string bandValue, string postcode, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TestDataGenerator"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Iterations", iterations);
            argumentsOfScenario.Add("bandValue", bandValue);
            argumentsOfScenario.Add("Postcode", postcode);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("NP_TD02_Band_NewProperty Creation with Modified Band Values", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 144
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 146
 await testRunner.GivenAsync(string.Format("I run the scenario {0} times", iterations), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 147
 await testRunner.GivenAsync("User uses test data with ID \'NP_003\' from \'TestDataPart3\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 148
 await testRunner.GivenAsync("User is logged in", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 149
 await testRunner.GivenAsync("User click on \'Submissions\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 150
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 151
 await testRunner.AndAsync("User looked for \'Integration Data Source\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 152
 await testRunner.AndAsync("User looked for \'Submitted By\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 153
 await testRunner.AndAsync("User looked for \'Relationship Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 154
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 155
 await testRunner.AndAsync("User scroll to \'Related Requests\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 156
 await testRunner.AndAsync("User click \'New Request\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
 await testRunner.AndAsync("User looked for \'Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 159
 await testRunner.AndAsync("User entered date for \'Proposed Effective Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 160
 await testRunner.AndAsync("User click on \'Find Address\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 161
 await testRunner.AndAsync("user enters data in \"Postcode\" and selects unique address for new property with d" +
                        "b data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 165
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 166
 await testRunner.AndAsync("User looked for \'Data Source Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 167
 await testRunner.AndAsync("User enter data for \'BA Report Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 168
 await testRunner.AndAsync("User enter data for \'Reason for Portal Reference Omission\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 169
 await testRunner.AndAsync("User enter data for \'Reason For Validation\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 170
 await testRunner.AndAsync("User enter random number for \'Proposed BA Reference Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 171
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 172
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 173
 await testRunner.AndAsync("User validate \'Validating\' status of \'Request\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 175
 await testRunner.AndAsync("User clicks on \'Submit Job\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 176
 await testRunner.AndAsync("User clicks on \'Proceed\' button on \'Confirm\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 177
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 178
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 179
 await testRunner.AndAsync("User waits till \'dialog\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 180
 await testRunner.AndAsync("User validate \'In Progress\' status of \'Request\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 181
 await testRunner.AndAsync("User click on \'Related Jobs\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 182
 await testRunner.AndAsync("User captures \"Job ID\" and \"Job Name\" in \"scenarioContext\" by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 183
 await testRunner.AndAsync("User click on \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 184
 await testRunner.AndAsync("User validate \'Researching\' status of \'Job\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 185
 await testRunner.AndAsync("User waits till \'Details\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 186
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 187
 await testRunner.AndAsync("User \'Assign\' job to self on \'Assign to Team or User\' pop-up", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 188
 await testRunner.AndAsync("user waits till app progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 189
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Details\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 190
 await testRunner.AndAsync("User waits till \'Researching\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 197
 await testRunner.AndAsync("User clicked on \'PVT\' tab under \'Desktop Research Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 198
 await testRunner.AndAsync("User clicked on \'Create\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 200
 await testRunner.AndAsync("User clicks on \'Save and continue\' button on \'Unsaved changes\' dialog,if appears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 201
 await testRunner.AndAsync("User looked for first element \'Group\' field value only when data not entered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 202
 await testRunner.AndAsync("User looked for first element \'Type\' field value only when data not entered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 203
 await testRunner.AndAsync("User looked for first element \'Age Code\' field value only when data not entered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 204
 await testRunner.AndAsync("User enter data for \'Area\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 205
 await testRunner.AndAsync("User enter data for \'Rooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 206
 await testRunner.AndAsync("User enter data for \'Bedrooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 207
 await testRunner.AndAsync("User enter data for \'Bathrooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 208
 await testRunner.AndAsync("User enter data for \'Floors\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 209
 await testRunner.AndAsync("User enter data for \'Level\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 210
 await testRunner.AndAsync("User looked for \'Parking\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 211
 await testRunner.AndAsync("User looked for \'Conservatory Type\' field value only when data not entered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 212
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 213
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 214
 await testRunner.AndAsync("User clicked on \'Add New Source Code\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 215
 await testRunner.AndAsync("User looked for \'Source Code\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 216
 await testRunner.AndAsync("User enter data for \'Comment\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 217
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 218
 await testRunner.AndAsync("user waits till app progress indicator disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 219
 await testRunner.AndAsync("User scroll to \'PAD Validation\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 220
 await testRunner.AndAsync("User click on \'Validate PAD Code\' toggle button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 221
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 222
 await testRunner.AndAsync("user wait till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 223
 await testRunner.AndAsync("User validate value \'Pass\' for \'PAD Validation Outcome\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 224
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 225
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 226
 await testRunner.AndAsync("User waits till \'Undertake Banding\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 227
 await testRunner.AndAsync("User clicked on \'Undertake Banding\' BPF Journey button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 228
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 229
 await testRunner.AndAsync("User closes business process stage container", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 230
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Banding\' tab display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 231
 await testRunner.AndAsync("User clicked on \'Banding\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 233
 await testRunner.AndAsync(string.Format("User looked for \'Proposed Tax Band\' {0} single character field value", bandValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 234
 await testRunner.AndAsync("User selects \'Yes\' value for \'Is Banding Complete?\' dropdown field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 235
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 236
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 238
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Undertake Banding\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 239
 await testRunner.AndAsync("User waits till \'Maintain Assessment\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 240
 await testRunner.AndAsync("User closes business process stage container", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 241
 await testRunner.AndAsync("User clicked on \'Assessment\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 242
 await testRunner.AndAsync("User waits till ProgressRing disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 244
 await testRunner.AndAsync("User switchs to Assessment frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 246
 await testRunner.AndAsync("User clicked on \'Proposed Assessments\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 247
 await testRunner.AndAsync("user asserts \'Proposed Assessments\' row count \'1\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 248
 await testRunner.AndAsync("User switchs to deafult frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 249
 await testRunner.AndAsync("User clicked on \'Maintain Assessment\' BPF Journey button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 250
 await testRunner.AndAsync("User selects \'No\' value for \'Correspondence Checks Complete?\' dropdown field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 251
 await testRunner.AndAsync("User selects \'Yes\' value for \'Maintain Assessment Complete?\' dropdown field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 252
 await testRunner.AndAsync("User clicks on \'Yes\' button on \'All Jobs Created for Request\' dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 253
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'List Updated\' status displa" +
                        "y", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 254
 await testRunner.AndAsync("User clicked on \'Details\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 255
 await testRunner.AndAsync("User scroll to \'Hereditament Details\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 256
 await testRunner.AndAsync("User captures \'Address String\' input field in \'scenarioContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 257
 await testRunner.AndAsync("User captures \'Job ID\' input field in \'scenarioContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 258
 await testRunner.AndAsync("User captures the \'Job ID\',\'Address String\' data in the \'NewPropOutPutData\' outpu" +
                        "t sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("NE_TD03_New Esatate Creation")]
        [global::NUnit.Framework.CategoryAttribute("TestDataGenerator")]
        [global::NUnit.Framework.TestCaseAttribute("1", "C", "180", "100", "1", "CF14 3UX", "1", "7", null)]
        public async global::System.Threading.Tasks.Task NE_TD03_NewEsatateCreation(string iterations, string bandValue, string plotsize, string numberOfPlots, string pageNum, string postcode, string position, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TestDataGenerator"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Iterations", iterations);
            argumentsOfScenario.Add("bandValue", bandValue);
            argumentsOfScenario.Add("plotsize", plotsize);
            argumentsOfScenario.Add("numberOfPlots", numberOfPlots);
            argumentsOfScenario.Add("pageNum", pageNum);
            argumentsOfScenario.Add("postcode", postcode);
            argumentsOfScenario.Add("position", position);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("NE_TD03_New Esatate Creation", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 269
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 271
 await testRunner.GivenAsync(string.Format("I run the scenario {0} times", iterations), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 272
 await testRunner.GivenAsync("User uses test data with ID \'Estate_TD_001\' from \'Estate_TG\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 273
 await testRunner.GivenAsync("User is logged in to Dynamics application to work for \"NewEstate_TD_Generator\" ca" +
                        "se", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 274
 await testRunner.AndAsync("User collapse if site map navigation expanded on left pane", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 275
 await testRunner.GivenAsync("User click on \'Estate Files\' under \'Navigate Dynamics 365\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 276
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 277
 await testRunner.AndAsync("User looked for \'Billing Authority\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 278
 await testRunner.AndAsync("User enter data for \'Development Name\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 279
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 280
 await testRunner.AndAsync("user waits for \'5\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 281
 await testRunner.AndAsync("User click on \'Launch VMS\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 282
 await testRunner.AndAsync("User should validate the VMS title as \'VMS - Valuation Mapping System\' and create" +
                        " estate extent for estate file", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 283
 await testRunner.AndAsync("user waits for \'5\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 284
 await testRunner.AndAsync("User click on \'Addresses\' tab from \'Estate File Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 285
 await testRunner.AndAsync(string.Format("user enters data in {0} and selects all address for estates", postcode), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 287
 await testRunner.AndAsync("user waits for \'5\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 288
 await testRunner.AndAsync("User click on \'Estate Actions\' tab from \'Estate File Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 289
 await testRunner.AndAsync("User clicks on \'New Estate Action\' button element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 290
 await testRunner.AndAsync("User looked for \'Estate Action Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 291
 await testRunner.AndAsync(string.Format("User enter data for \'Number of Plots\' field value with value {0}", numberOfPlots), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 292
 await testRunner.AndAsync("User enter data for \'Plot Starting Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 293
 await testRunner.AndAsync("User click on \'Submit\' toggle button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 294
 await testRunner.AndAsync("User clicked on \'Save and Close\' button on new UI", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 295
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 296
 await testRunner.AndAsync("user waits for \'5\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 297
 await testRunner.AndAsync("User click on \'House Types\' tab from \'Estate File Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 298
 await testRunner.AndAsync("User clicks on \'New House Type\' button element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 299
 await testRunner.AndAsync("User enter data for 2 position \'Name\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 300
 await testRunner.AndAsync("User looked for 2 position \'Group\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 301
 await testRunner.AndAsync("User looked for \'Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 302
 await testRunner.AndAsync("User looked for \'List\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 303
 await testRunner.AndAsync("User clicked on \'Save and Close\' button on new UI", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 304
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 305
 await testRunner.AndAsync("User click on newly created house type", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 306
 await testRunner.AndAsync("User waits till \'Validate PAD\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 307
 await testRunner.AndAsync("User enter data for \'Area\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 308
 await testRunner.AndAsync("User enter data for \'Rooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 309
 await testRunner.AndAsync("User enter data for \'Bedrooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 310
 await testRunner.AndAsync("User enter data for \'Bathrooms\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 311
 await testRunner.AndAsync("User enter data for \'Floors\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 312
 await testRunner.AndAsync("User looked for \'Parking\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 313
 await testRunner.AndAsync("User scroll to \'PAD Validation\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 314
 await testRunner.AndAsync("User click on \'Validate PAD Code\' toggle button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 315
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 316
 await testRunner.AndAsync("User validate value \'Pass\' for \'PAD Validation Outcome\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 317
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 318
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Validate PAD\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 319
 await testRunner.AndAsync("User waits till \'Banding\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 320
 await testRunner.AndAsync("User closes business process stage container", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 321
 await testRunner.AndAsync("User clicked on \'Banding\' tab under \'House Type Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 322
  await testRunner.AndAsync("User looked for \'Proposed Tax Band\' single character field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 323
 await testRunner.AndAsync("User clicks on \'Is Banding Complete?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 324
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 325
 await testRunner.AndAsync("user wait till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 326
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 327
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 328
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 329
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 330
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 331
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 332
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 333
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 334
 await testRunner.AndAsync("User waits till \'Approve House Type\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 335
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 336
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 337
 await testRunner.AndAsync("User clicked on \'Approvals\' tab under \'House Type Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 338
 await testRunner.AndAsync("User looked for \'Approver\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 339
 await testRunner.AndAsync("User clicks on \'House Type Approved?\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 340
 await testRunner.AndAsync("User enter data for \'Outcome Reason\' text area field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 341
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 342
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Approved\' status display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 343
 await testRunner.AndAsync("User clicks on \'Go back\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 344
 await testRunner.AndAsync("user waits for \'5\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 345
 await testRunner.AndAsync("User click on \'Plot Manager\' tab from \'Estate File Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 346
 await testRunner.AndAsync(string.Format("User select Address Labels with iteration for {0},{1}", position, postcode), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 347
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 348
 await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("CBARef_TD04_Change of BA reference Auto Process")]
        [global::NUnit.Framework.CategoryAttribute("TestDataGenerator")]
        [global::NUnit.Framework.TestCaseAttribute("1", "8", null)]
        public async global::System.Threading.Tasks.Task CBARef_TD04_ChangeOfBAReferenceAutoProcess(string iterations, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TestDataGenerator"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Iterations", iterations);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CBARef_TD04_Change of BA reference Auto Process", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 357
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 359
 await testRunner.GivenAsync(string.Format("I run the scenario {0} times", iterations), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 360
 await testRunner.GivenAsync("User uses test data with ID \'BAR_001\' from \'TestDataPart3\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table334 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table334.AddRow(new string[] {
                            "town"});
                table334.AddRow(new string[] {
                            "postcode"});
                table334.AddRow(new string[] {
                            "uprn"});
#line 361
 await testRunner.AndAsync("User connects to the DB and retrieves the data for \'findHereditament_UAT\'", ((string)(null)), table334, "And ");
#line hidden
#line 366
 await testRunner.GivenAsync("User is logged in to Dynamics application to work for \"BAref_TD_Generator\" case", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 367
 await testRunner.GivenAsync("User click on \'Submissions\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 368
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 369
 await testRunner.AndAsync("User looked for \'Integration Data Source\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 370
 await testRunner.AndAsync("User looked for \'Submitted By\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 371
 await testRunner.AndAsync("User looked for \'Relationship Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 372
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 373
 await testRunner.AndAsync("User scroll to \'Related Requests\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 374
 await testRunner.AndAsync("User click \'New Request\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 375
 await testRunner.AndAsync("User looked for \'Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 376
 await testRunner.AndAsync("User entered 0 days before date for \'Date Received\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 377
 await testRunner.AndAsync("User entered 25 days before date for \'Proposed Effective Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 378
 await testRunner.AndAsync("User looked for \'Data Source Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 379
 await testRunner.AndAsync("User enter data for \'BA Report Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 380
 await testRunner.AndAsync("User enter data for \'Reason For Validation\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 381
 await testRunner.AndAsync("User enter data for \'Remarks\' text area field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 382
 await testRunner.AndAsync("User click on \'Find Hereditament\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 383
 await testRunner.AndAsync("User enters data in \"Postcode\" field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 384
 await testRunner.AndAsync("User clicked on \'Search\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 385
 await testRunner.AndAsync("User slects spcific \'uprn\' row from search hereditament results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 386
 await testRunner.AndAsync("User clicked on \'Select\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 387
 await testRunner.AndAsync("User waits till Find Hereditament dialog disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 388
 await testRunner.AndAsync("User scroll to \'Billing Authority Link\' section and enter data in \'Proposed BA Re" +
                        "ference Number\' field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 389
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 390
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 391
 await testRunner.AndAsync("User validate \'Validating\' status of \'Request\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 392
 await testRunner.AndAsync("User clicks on \'Validate Request\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 393
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 394
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 395
 await testRunner.AndAsync("User waits till \'dialog\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 396
 await testRunner.AndAsync("User click on \'BA Reference\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 397
 await testRunner.AndAsync("user waits for \'10\' secs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 398
 await testRunner.AndAsync("User clicks on \'New Proposed BA Reference Amendment\' button element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 399
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 400
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 401
 await testRunner.AndAsync("User clicks on \'Validate For Autoprocess\' dropdown and select \'Yes\' value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 402
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 403
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 404
 await testRunner.AndAsync("User click on \'Related Jobs\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 405
 await testRunner.AndAsync("User captures \"Job ID\" and \"Job Name\" in \"scenarioContext\" by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 406
 await testRunner.AndAsync("User click on \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 407
 await testRunner.AndAsync("User click on \'Refresh\' button from \'menubar\' untill \'Resolved\' status display", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 408
 await testRunner.AndAsync("User clicked on \'Details\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 409
 await testRunner.AndAsync("User scroll to \'Hereditament Details\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 410
 await testRunner.AndAsync("User captures \'Address String\' input field in \'scenarioContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 411
 await testRunner.AndAsync("User captures \'Job ID\' input field in \'scenarioContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 412
 await testRunner.AndAsync("User captures the \'Job ID\',\'Address String\' data in the \'NewPropOutPutData\' outpu" +
                        "t sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 413
 await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("MR_TD05_Material Reduction request and Job Test Data Genarator")]
        [global::NUnit.Framework.CategoryAttribute("TestDataGenerator")]
        [global::NUnit.Framework.TestCaseAttribute("1", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("2", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("3", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("4", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("5", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("6", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("7", "15", null)]
        [global::NUnit.Framework.TestCaseAttribute("8", "16", null)]
        public async global::System.Threading.Tasks.Task MR_TD05_MaterialReductionRequestAndJobTestDataGenarator(string iterations, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TestDataGenerator"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Iterations", iterations);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("MR_TD05_Material Reduction request and Job Test Data Genarator", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 421
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 422
 await testRunner.GivenAsync(string.Format("I run the scenario {0} times", iterations), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 423
 await testRunner.GivenAsync("User uses test data with ID \'MR_001\' from \'TestDataPart3\' sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table335 = new global::Reqnroll.Table(new string[] {
                            "fieldName"});
                table335.AddRow(new string[] {
                            "town"});
                table335.AddRow(new string[] {
                            "postcode"});
                table335.AddRow(new string[] {
                            "uprn"});
#line 424
 await testRunner.AndAsync("User connects to the DB and retrieves the data for \'findHereditament_UAT\'", ((string)(null)), table335, "And ");
#line hidden
#line 429
 await testRunner.GivenAsync("User is logged in to Dynamics application to work for \"BST-80539_CR07\" case", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 430
 await testRunner.GivenAsync("User click on \'Submissions\' under \'Service\' section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 431
 await testRunner.AndAsync("User click on \'New\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 432
 await testRunner.AndAsync("User looked for \'Integration Data Source\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 433
 await testRunner.AndAsync("User looked for \'Submitted By\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 434
 await testRunner.AndAsync("User looked for \'Relationship Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 435
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 436
 await testRunner.AndAsync("User scroll to \'Related Requests\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 437
 await testRunner.AndAsync("User click \'New Request\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 438
 await testRunner.AndAsync("User looked for \'Job Type\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 439
 await testRunner.AndAsync("User entered 0 days before date for \'Date Received\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 440
 await testRunner.AndAsync("User entered 25 days before date for \'Proposed Effective Date\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 441
 await testRunner.AndAsync("User looked for \'Data Source Role\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 442
 await testRunner.AndAsync("User enter data for \'BA Report Number\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 443
 await testRunner.AndAsync("User enter data for \'Reason For Validation\' field value", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 444
 await testRunner.AndAsync("User click on \'Find Hereditament\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 445
 await testRunner.AndAsync("User enters data in \"Postcode\" field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 446
 await testRunner.AndAsync("User clicked on \'Search\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 447
 await testRunner.AndAsync("User slects spcific \'uprn\' row from search hereditament results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 448
 await testRunner.AndAsync("User clicked on \'Select\' button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 449
 await testRunner.AndAsync("User waits till Find Hereditament dialog disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 450
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 451
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 452
 await testRunner.AndAsync("User click on \'Save\' button from \'menubar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 453
 await testRunner.AndAsync("user waits till \'Saving...\' \'progressbar\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 454
 await testRunner.AndAsync("User validate \'Validating\' status of \'Request\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 455
 await testRunner.AndAsync("User clicks on \'Validate Request\' under \'Request Action\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 456
 await testRunner.AndAsync("User click on \'Save & Close\' button from \'dialog\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 457
 await testRunner.AndAsync("User waits till \'dialog\' disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 458
 await testRunner.AndAsync("User validate \'In Progress\' status of \'Request\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 459
 await testRunner.AndAsync("User click on \'Related Jobs\' tab from \'Request Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 460
 await testRunner.AndAsync("User captures \"Job ID\" and \"Job Name\" in \"scenarioContext\" by \"Refresh\" grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 461
 await testRunner.AndAsync("User click on \"Job Id\" element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 462
 await testRunner.AndAsync("User waits till \'Details\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 463
 await testRunner.AndAsync("User \'Assign\' job to self on \'Assign to Team or User\' pop-up", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 464
 await testRunner.AndAsync("user waits till loading spinner disappears", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 465
 await testRunner.AndAsync("User clicked on \'Details\' tab under \'Job Form\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 466
 await testRunner.AndAsync("User scroll to \'Hereditament Details\' element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 467
 await testRunner.AndAsync("User captures \'Address String\' input field in \'scenarioContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 468
 await testRunner.AndAsync("User captures \'Job ID\' input field in \'scenarioContext\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 469
 await testRunner.AndAsync("User captures the \'Job ID\',\'Address String\' data in the \'NewPropOutPutData\' outpu" +
                        "t sheet", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 470
 await testRunner.AndAsync("User clicked on \'Next Stage\' for \'Details\' journey on the headerbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 471
 await testRunner.AndAsync("User waits till \'Researching\' stage selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 472
 await testRunner.AndAsync("User closes browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
